# Generated by Django 6.0.4 on 2026-07-13 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amrit_sites', '0004_roledefinition_dynamic_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
                ('datasets', models.JSONField(default=list)),
                ('fields', models.JSONField(default=list)),
                ('legal_basis', models.CharField(max_length=240)),
                ('ethics_reference', models.CharField(blank=True, max_length=160)),
                ('minimisation_json', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(db_index=True, default='submitted', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_access_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('sector', models.CharField(choices=[], max_length=24)),
                ('severity', models.CharField(max_length=16)),
                ('state', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('investigating', 'Investigating'), ('controlled', 'Controlled'), ('closed', 'Closed'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('scope_type', models.CharField(max_length=16)),
                ('scope_value', models.CharField(blank=True, max_length=160)),
                ('signal_json', models.JSONField(default=dict)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sector', models.CharField(choices=[('human', 'Human'), ('animal', 'Animal'), ('fisheries', 'Fisheries'), ('food', 'Food'), ('environment', 'Environment'), ('genomics', 'Genomics'), ('cross_sector', 'Cross Sector')], db_index=True, max_length=24)),
                ('module_key', models.CharField(db_index=True, max_length=64)),
                ('contract', models.CharField(max_length=160)),
                ('contract_version', models.CharField(default='1.0', max_length=32)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('payload_json', models.JSONField(default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('record_count', models.PositiveBigIntegerField(default=0)),
                ('quality_json', models.JSONField(blank=True, default=dict)),
                ('lineage_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='submitted', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_products', to='amrit_sites.site')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_key', models.CharField(max_length=128, unique=True)),
                ('certificate_serial', models.CharField(blank=True, db_index=True, max_length=128)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('schema_version', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('compliant', 'Compliant'), ('noncompliant', 'Non-compliant'), ('revoked', 'Revoked')], db_index=True, default='provisioning', max_length=16)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('health_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='amrit_sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='JointRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('hazard', models.CharField(max_length=200)),
                ('geography', models.CharField(blank=True, max_length=200)),
                ('sectors', models.JSONField(default=list)),
                ('components_json', models.JSONField(default=dict, help_text='Likelihood, impact, exposure, uncertainty and evidence components.')),
                ('score', models.FloatField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=32)),
                ('uncertainty', models.CharField(blank=True, max_length=32)),
                ('rationale', models.TextField()),
                ('status', models.CharField(choices=[], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ManyToManyField(blank=True, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('organization_type', models.CharField(choices=[('national', 'National'), ('ministry', 'Ministry'), ('state', 'State'), ('district', 'District'), ('facility', 'Facility'), ('laboratory', 'Laboratory'), ('research', 'Research'), ('regulator', 'Regulator')], max_length=24)),
                ('state_code', models.CharField(blank=True, max_length=16)),
                ('district_code', models.CharField(blank=True, max_length=16)),
                ('identifiers', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ecosystem.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework', models.CharField(default='NAP-AMR 2.0', max_length=80)),
                ('objective_code', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('state_code', models.CharField(blank=True, db_index=True, max_length=16)),
                ('period', models.CharField(max_length=32)),
                ('target_json', models.JSONField(default=dict)),
                ('actual_json', models.JSONField(blank=True, default=dict)),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(db_index=True, default='not_started', max_length=24)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('evidence_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='ecosystem.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('GLASS', 'GLASS'), ('ANIMUSE', 'ANIMUSE'), ('InFARM', 'InFARM'), ('NAP-AMR', 'NAP-AMR'), ('Public annual report', 'Public annual report')], max_length=32)),
                ('period', models.CharField(max_length=32)),
                ('parameters_json', models.JSONField(default=dict)),
                ('code_version', models.CharField(max_length=80)),
                ('output_sha256', models.CharField(blank=True, max_length=64)),
                ('output_url', models.URLField(blank=True)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('validation_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('input_products', models.ManyToManyField(blank=True, related_name='reporting_runs', to='ecosystem.dataproduct')),
            ],
        ),
        migrations.CreateModel(
            name='TerminologyRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_type', models.CharField(db_index=True, max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('sha256', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('download_url', models.URLField()),
                ('effective_at', models.DateTimeField()),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('package_type', 'version'), name='unique_terminology_release')],
            },
        ),
        migrations.AddIndex(
            model_name='dataproduct',
            index=models.Index(fields=['sector', 'module_key', '-received_at'], name='ecosystem_d_sector_f95fb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='dataproduct',
            constraint=models.UniqueConstraint(fields=('site', 'module_key', 'payload_sha256'), name='unique_site_product_payload'),
        ),
    ]
