# Generated by Django 6.0.4 on 2026-07-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcase',
            name='sector',
            field=models.CharField(choices=[('human', 'Human'), ('animal', 'Animal'), ('fisheries', 'Fisheries'), ('food', 'Food'), ('environment', 'Environment'), ('genomics', 'Genomics'), ('cross_sector', 'Cross Sector')], max_length=24),
        ),
        migrations.AlterField(
            model_name='jointriskassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
    ]
