# Generated by Django 5.0.7 on 2026-05-01 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amrit_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('isolate_count', 'Isolate count'), ('organism_distribution', 'Organism distribution'), ('specimen_distribution', 'Specimen distribution'), ('resistance_rate', 'Resistance rate'), ('measure_bundle', 'FHIR MeasureReport bundle')], db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('target_lab_codes', models.JSONField(blank=True, default=list)),
                ('antibiotic_code', models.CharField(blank=True, max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatched', 'Dispatched'), ('partial', 'Partial'), ('completed', 'Completed'), ('expired', 'Expired'), ('error', 'Error'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amrit_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='amrit_sites.site')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queries.query')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('answered', 'Answered'), ('error', 'Error'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='queries.query')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='amrit_sites.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'status'], name='queries_que_site_id_95289c_idx'), models.Index(fields=['query', 'status'], name='queries_que_query_i_b63852_idx')],
                'unique_together': {('query', 'site')},
            },
        ),
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='queries.query')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='amrit_sites.site')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['query', 'received_at'], name='queries_que_query_i_064dd4_idx'), models.Index(fields=['site', 'received_at'], name='queries_que_site_id_1a90f1_idx')],
            },
        ),
    ]
