# Generated by Django 6.0.4 on 2026-06-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrit_sites', '0002_site_latitude_site_longitude_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
