# Generated by Django 6.0.4 on 2026-08-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amrit_sites", "0004_roledefinition_dynamic_roles"),
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="admin_path",
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AddField(
            model_name="site",
            name="admin_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="geo.adminunit",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AddField(
            model_name="site",
            name="timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="admin_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="geo.adminunit",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_code",
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
    ]
