# Generated by Django 6.0.4 on 2026-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amrit_sites", "0006_link_sites_to_admin_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="roledefinition",
            name="scope_level",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roledefinition",
            name="scope_kind",
            field=models.CharField(
                choices=[
                    ("none", "No sites"),
                    ("all", "All sites"),
                    ("state", "Profile state"),
                    ("district", "Profile state + district"),
                    ("site", "Assigned site"),
                    ("admin", "Profile administrative unit"),
                    ("country", "Profile country"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
