# Generated by Django 6.0.4 on 2026-08-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryConfig",
            fields=[
                (
                    "country_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("profile_id", models.CharField(blank=True, max_length=32)),
                ("overrides", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["country_code"],
            },
        ),
        migrations.CreateModel(
            name="AdminUnit",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("country_code", models.CharField(db_index=True, max_length=3)),
                ("level", models.PositiveSmallIntegerField(db_index=True)),
                ("code", models.CharField(max_length=64)),
                ("code_system", models.CharField(default="ISO3166-2", max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("name_local", models.CharField(blank=True, max_length=200)),
                ("unit_type", models.CharField(blank=True, max_length=64)),
                ("admin_path", models.CharField(db_index=True, max_length=512)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("source_dataset", models.CharField(blank=True, max_length=64)),
                ("source_version", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="geo.adminunit",
                    ),
                ),
            ],
            options={
                "ordering": ["country_code", "level", "sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["country_code", "level"],
                        name="geo_adminun_country_2a31f1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "level", "code"),
                        name="uniq_admin_unit_country_level_code",
                    )
                ],
            },
        ),
    ]
