import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { AddressFormatPack, CountryAddressFormat } from '../shared/address.js'

/**
 * Loads the bundled address-format pack.
 *
 * The pack is generated by `tools/generate_address_formats.py` and checked in, so this
 * only reads it. Nothing here carries per-country knowledge: a country the pack does not
 * cover falls back to the pack's own default entry, which is a working address form rather
 * than an error, so a deployment in an unlisted territory is never blocked from recording
 * where its laboratories are.
 */

export const ADDRESS_FORMAT_RESOURCE = 'shared/address-formats/address-formats.v1.json'

function candidatePaths(relative: string): string[] {
  const moduleDirectory = dirname(fileURLToPath(import.meta.url))
  const resourcesPath = (process as NodeJS.Process & { resourcesPath?: string }).resourcesPath
  return [
    resourcesPath ? resolve(resourcesPath, 'resources', relative) : '',
    resolve(process.cwd(), 'resources', relative),
    resolve(moduleDirectory, '../../resources', relative)
  ].filter(Boolean)
}

let cached: AddressFormatPack | null = null

export function addressFormatPack(): AddressFormatPack {
  if (cached) return cached
  for (const candidate of candidatePaths(ADDRESS_FORMAT_RESOURCE)) {
    if (!existsSync(candidate)) continue
    const pack = JSON.parse(readFileSync(candidate, 'utf8')) as AddressFormatPack
    if (!pack.default || !pack.countries) {
      throw new Error(`Address format pack at ${candidate} is missing its default entry or country table.`)
    }
    cached = pack
    return cached
  }
  throw new Error(
    `Address format pack not found. Expected ${ADDRESS_FORMAT_RESOURCE} in the packaged resources; ` +
      'run python3 tools/sync_shared.py if this is a source checkout.'
  )
}

/** The address form for a country. Falls back to the pack default, never throws. */
export function addressFormatFor(countryCode: string): CountryAddressFormat {
  const pack = addressFormatPack()
  const key = String(countryCode ?? '').trim().toUpperCase()
  return pack.countries[key] ?? pack.default
}

/** Test seam: the pack is cached for the process lifetime, and tests swap profiles. */
export function resetAddressFormatCache(): void {
  cached = null
}
