import { app, BrowserWindow, dialog, ipcMain, Menu, nativeImage, session, shell, type IpcMainInvokeEvent, type MenuItemConstructorOptions, type OpenDialogOptions } from 'electron'
import { basename, extname, join, resolve } from 'node:path'
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'

import { setActiveCountryProfile } from './active-profile'
import { AMRITDatabase } from './database'
import { availableCountries, clearCountryProfileCache, getCountryProfile } from './country-profile'
import { addressFormatFor } from './address-format'
import { resolveResourcePath } from './catalog-seed'
import { lookupLocality, lookupPostalCode } from './geo-directory'
import {
  expand as expandTerminology, loadTerminologySeed, lookup as lookupTerminology, profileGate
} from './terminology'
import { dataLicences } from './data-licences'
import { DEMO_ONE_HEALTH_ADMIN, seedDemoData } from './demo-seed'
import {
  MAX_LOGO_PIXELS,
  applyOverrides,
  irreversibleChanges,
  logoDataUri,
  overridesFromProfile,
  validateLogo,
  validateOverrides
} from './deployment-config'
import { rebuildOneHealthModules } from './one-health-engine'
import { CredentialVault } from './credentials'
import { animuseProduct, glassProduct, infarmProduct, type OneHealthExportFormat } from './one-health-exporters'
import { OneHealthSession, requirePermission } from './one-health-governance'
import { attachOmicsFile, removeStoredOmicsFile } from './omics'
import { resolveDatabaseLocation, type DatabaseLocation } from './paths'
import {
  BREAKPOINT_SOURCES,
  OFFICIAL_BREAKPOINT_URLS,
  availableBreakpointSources,
  breakpointSource,
  SUPPORTED_QUERY_TYPES,
  SyncManager,
  askLLM,
  createAggregateExecutor,
  createExport,
  createImportTemplate,
  deleteLocalModel,
  downloadOfficialBreakpointFile,
  updateEucastBreakpoints,
  importBreakpointWorkbook,
  listLocalModels,
  parseImportPreview,
  pullLocalModel,
  testLLM,
  type LLMProvider,
  type LLMServiceConfig
} from './services'
import { channels } from '../shared/channels'
import type { AppBootstrap, CountryOption, CountryProfile, ImportPreview, ImportProfile, IsolateRecord, Row, SyncConfig, SyncStatus } from '../shared/types'
import {
  analysisFiltersSchema,
  assertHttpUrl,
  codeSchema,
  fileOptionsSchema,
  filtersSchema,
  idSchema,
  importPreviewSchema,
  importProfileSchema,
  laboratorySchema,
  masterKindSchema,
  modelNameSchema,
  moduleKeySchema,
  pathSchema,
  preferencesSchema,
  recordSchema,
  rowSchema,
  saveOptionsSchema,
  scalarKeySchema,
  sourceSchema,
  syncConfigSchema
} from './validation'

const currentDirectory = fileURLToPath(new URL('.', import.meta.url))
/**
 * The offline fallback for the EUCAST update.
 *
 * Generated by `tools/fetch_eucast_breakpoints.py` from EUCAST's own published workbook and
 * checked in by a maintainer, so a laboratory with no outbound network still gets real
 * breakpoints. Absent from a source checkout, which is why every read of it is guarded: an
 * empty install and a failed fetch must produce a clear message, never invented thresholds.
 */
const EUCAST_BUNDLED_FILENAME = 'breakpoints/eucast-breakpoints.json'
const eucastBundledPath = (): string => resolveResourcePath(EUCAST_BUNDLED_FILENAME)
const SECRET_PREFERENCE_KEYS = new Set(['sync_auth_token', 'sync_site_token', 'llm_api_key', 'sync.authToken', 'sync.siteToken', 'llm.apiKey'])
const SYNC_TOKEN_KEY = 'sync.auth-token'
const SITE_TOKEN_KEY = 'sync.site-token'
// Kept in the vault with the other two rather than in preferences: it collects a credential,
// so it is one in every sense that matters.
const PICKUP_TOKEN_KEY = 'sync.pickup-token'
const LLM_KEY = 'llm.api-key'
const oneHealthUsernameSchema = z.string().trim().regex(/^[A-Za-z0-9._-]{3,64}$/)
const oneHealthPasswordSchema = z.string().min(1).max(1_024)
const oneHealthNewPasswordSchema = z.string().min(12).max(1_024)
const oneHealthRoleSchema = z.enum(['administrator', 'data-entry', 'reviewer', 'steward', 'auditor', 'sync-agent'])
const oneHealthExportSchema = z.enum(['aggregate', 'glass', 'animuse', 'infarm'])
const oneHealthActionStatusSchema = z.enum(['open', 'in-progress', 'blocked', 'closed', 'cancelled'])
const oneHealthReviewStatusSchema = z.enum(['reviewed', 'dismissed', 'escalated'])

let mainWindow: BrowserWindow | null = null
let database: AMRITDatabase
let databaseLocation: DatabaseLocation
let vault: CredentialVault
let syncManager: SyncManager
let enrolmentController: AbortController | null = null
const oneHealthSession = new OneHealthSession()
const approvedReadPaths = new Set<string>()
const approvedWritePaths = new Set<string>()

function boolPreference(value: string | undefined, fallback = false): boolean {
  if (value === undefined || value === '') return fallback
  return ['1', 'true', 'yes', 'on'].includes(value.toLocaleLowerCase())
}

function integerPreference(value: string | undefined, fallback: number, minimum: number, maximum: number): number {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? Math.max(minimum, Math.min(maximum, Math.trunc(parsed))) : fallback
}

function numberPreference(value: string | undefined): number | undefined {
  if (!String(value ?? '').trim()) return undefined
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : undefined
}

function errorMessage(error: unknown): string {
  if (error instanceof z.ZodError) return error.issues.map((issue) => `${issue.path.join('.') || 'input'}: ${issue.message}`).join('; ')
  return error instanceof Error ? error.message : String(error)
}

function approvedPath(rawPath: unknown, mode: 'read' | 'write'): string {
  const candidate = resolve(pathSchema.parse(rawPath))
  const approved = mode === 'read' ? approvedReadPaths : approvedWritePaths
  if (!approved.has(candidate)) throw new Error(`Select the ${mode === 'read' ? 'input file' : 'destination'} through AMRIT first.`)
  return candidate
}

/**
 * Whether a URL is this application's own renderer.
 *
 * Used for permissions as well as for IPC: a permission granted to "the window" would be
 * granted to whatever that window had been navigated to.
 */
function isOwnContent(raw: string): boolean {
  try {
    const url = new URL(raw)
    const developmentUrl = process.env.ELECTRON_RENDERER_URL
    if (developmentUrl) return url.origin === new URL(developmentUrl).origin
    return url.protocol === 'file:' && url.pathname.endsWith('/out/renderer/index.html')
  } catch {
    return false
  }
}

function isTrustedSender(event: IpcMainInvokeEvent): boolean {
  const raw = event.senderFrame?.url || event.sender.getURL()
  try {
    const url = new URL(raw)
    const developmentUrl = process.env.ELECTRON_RENDERER_URL
    if (developmentUrl) return url.origin === new URL(developmentUrl).origin
    return url.protocol === 'file:' && url.pathname.endsWith('/out/renderer/index.html')
  } catch {
    return false
  }
}

function handle(channel: string, callback: (...args: unknown[]) => unknown | Promise<unknown>): void {
  ipcMain.removeHandler(channel)
  ipcMain.handle(channel, async (event, ...args) => {
    if (!isTrustedSender(event)) throw new Error('Rejected IPC from an untrusted renderer.')
    try {
      return await callback(...args)
    } catch (error) {
      const message = errorMessage(error)
      try { database?.recordAudit('ipc.error', 'error', `${channel}: ${message}`) } catch { /* database may not be ready */ }
      throw new Error(message)
    }
  })
}

async function migrateLegacySecrets(): Promise<void> {
  const preferences = database.getPreferences()
  const migrations: Array<[string, string, string]> = [
    ['sync_auth_token', SYNC_TOKEN_KEY, preferences.sync_auth_token ?? ''],
    ['sync_site_token', SITE_TOKEN_KEY, preferences.sync_site_token ?? ''],
    ['llm_api_key', LLM_KEY, preferences.llm_api_key ?? '']
  ]
  const cleared: Record<string, string> = {}
  for (const [preferenceKey, vaultKey, value] of migrations) {
    if (value && !(await vault.get(vaultKey))) await vault.set(vaultKey, value)
    if (value) cleared[preferenceKey] = ''
  }
  if (Object.keys(cleared).length) {
    database.savePreferences(cleared)
    database.recordAudit('security.secret-migration', 'ok', 'Legacy plaintext credentials moved to the encrypted vault.')
  }
}

async function loadSyncConfig(overrides: Partial<SyncConfig> = {}): Promise<SyncConfig> {
  const preferences = database.getPreferences()
  const currentLab = database.currentLab()
  const configuredAllowed = preferences.sync_allowed_queries
  const allowed = (configuredAllowed === undefined ? SUPPORTED_QUERY_TYPES.join(',') : configuredAllowed)
    .split(',')
    .map((item) => item.trim())
    .filter((item) => (SUPPORTED_QUERY_TYPES as readonly string[]).includes(item))
  const base: SyncConfig = {
    serverUrl: preferences.sync_server_url ?? '',
    authToken: await vault.get(SYNC_TOKEN_KEY),
    siteToken: await vault.get(SITE_TOKEN_KEY),
    pickupToken: await vault.get(PICKUP_TOKEN_KEY),
    labCode: preferences.sync_lab_code || currentLab?.code || '',
    pollIntervalSeconds: integerPreference(preferences.sync_poll_interval, 30, 5, 86_400),
    pollTimeoutSeconds: integerPreference(preferences.sync_poll_timeout, 60, 5, 600),
    verifyTls: boolPreference(preferences.sync_verify_tls, true),
    autoConfigureToken: boolPreference(preferences.sync_auto_configure_token, true),
    gpsConsent: boolPreference(preferences.sync_gps_consent),
    gpsLatitude: numberPreference(preferences.sync_gps_latitude),
    gpsLongitude: numberPreference(preferences.sync_gps_longitude),
    gpsSource: preferences.sync_gps_source === 'device' ? 'device' as const : 'manual' as const,
    allowedQueryTypes: allowed
  }
  const combined = { ...base, ...overrides }
  // The renderer never receives these, so it cannot echo them back; an empty value from it
  // means "unchanged", not "clear it".
  if (!String(overrides.authToken ?? '').trim()) combined.authToken = base.authToken
  if (!String(overrides.siteToken ?? '').trim()) combined.siteToken = base.siteToken
  if (!String(overrides.pickupToken ?? '').trim()) combined.pickupToken = base.pickupToken
  return combined
}

async function saveSyncConfig(input: SyncConfig): Promise<SyncConfig> {
  const config = syncConfigSchema.parse(await loadSyncConfig(input))
  if (input.authToken) await vault.set(SYNC_TOKEN_KEY, input.authToken)
  if (input.siteToken) await vault.set(SITE_TOKEN_KEY, input.siteToken)
  if (input.pickupToken) await vault.set(PICKUP_TOKEN_KEY, input.pickupToken)
  database.savePreferences({
    sync_server_url: config.serverUrl,
    sync_lab_code: config.labCode,
    sync_poll_interval: String(config.pollIntervalSeconds),
    sync_poll_timeout: String(config.pollTimeoutSeconds),
    sync_verify_tls: config.verifyTls ? '1' : '0',
    sync_auto_configure_token: config.autoConfigureToken ? '1' : '0',
    sync_gps_consent: config.gpsConsent ? '1' : '0',
    sync_gps_latitude: config.gpsLatitude === undefined ? '' : String(config.gpsLatitude),
    sync_gps_longitude: config.gpsLongitude === undefined ? '' : String(config.gpsLongitude),
    sync_gps_source: config.gpsSource === 'device' ? 'device' : 'manual',
    sync_allowed_queries: config.allowedQueryTypes.join(','),
    sync_auth_token: '',
    sync_site_token: ''
  })
  database.recordAudit('sync.settings', 'ok', 'Sync settings saved without plaintext credentials.')
  return config
}

async function rendererSyncConfig(): Promise<SyncConfig> {
  const config = await loadSyncConfig()
  return { ...config, authToken: '', siteToken: '', pickupToken: '' }
}

/** Keep device-style approval polling in the main process, where pickup/auth secrets live. */
function beginAccessTokenCollection(
  config: SyncConfig,
  intervalSeconds = 5,
  pickupExpiresAt = ''
): void {
  enrolmentController?.abort()
  const controller = new AbortController()
  enrolmentController = controller
  void syncManager.waitForApproval(config, {
    intervalSeconds,
    pickupExpiresAt,
    signal: controller.signal
  }).then(async (approvedConfig) => {
    if (controller.signal.aborted) return
    if (!approvedConfig.authToken) throw new Error('The server approved access but did not return an authentication token.')
    await vault.remove(PICKUP_TOKEN_KEY)
    database.savePreferences({ sync_pickup_expires_at: '' })
    database.recordAudit(
      'sync.token.collect',
      'ok',
      'Approved authentication token collected automatically and encrypted in the OS credential vault.'
    )
    broadcastSyncStatus({ ...syncManager.getStatus(), tokenConfigured: true, lastError: '' })
  }).catch((error: unknown) => {
    if (controller.signal.aborted) return
    database.recordAudit('sync.token.collect', 'warning', errorMessage(error))
    broadcastSyncStatus({ ...syncManager.getStatus(), lastError: errorMessage(error) })
  }).finally(() => {
    if (enrolmentController === controller) enrolmentController = null
  })
}

/**
 * Resolve the active country profile.
 *
 * Order: AMRIT_COUNTRY_PROFILE, then the `country_profile_id` preference, then the neutral
 * fallback. Existing installs retain their stored choice; a new international install must
 * choose its country explicitly instead of silently inheriting one country's rules.
 */
const DEPLOYMENT_OVERRIDES_KEY = 'country_profile_overrides'

/** The administrator's stored overrides, or an empty document. */
function storedOverrides(): Record<string, unknown> {
  try {
    return JSON.parse(database.getPreferences()[DEPLOYMENT_OVERRIDES_KEY] || '{}') as Record<string, unknown>
  } catch {
    return {}
  }
}

function activeCountryProfile(): CountryProfile {
  const preferred = process.env.AMRIT_COUNTRY_PROFILE || database.getPreferences().country_profile_id
  let profile: CountryProfile
  try {
    profile = getCountryProfile(preferred)
  } catch (error) {
    // A bad preference must never stop the app from starting.
    console.error(`Country profile "${preferred}" could not be loaded; falling back.`, error)
    profile = getCountryProfile()
  }
  try {
    const overrides = storedOverrides()
    if (Object.keys(overrides).length) profile = applyOverrides(profile, overrides)
  } catch (error) {
    // Overrides that no longer validate must not brick the app; the base profile still works.
    console.error('Stored deployment settings could not be applied; using the base profile.', error)
  }
  // Publish to the process-wide holder the pure modules read, and refresh the One Health
  // field labels, which are derived from the profile's administrative levels.
  setActiveCountryProfile(profile)
  rebuildOneHealthModules()
  return profile
}

/**
 * Validate, store and publish a complete override document.
 *
 * Save, logo upload and profile import all land here so the irreversible-namespace rule and
 * the merged-profile validation cannot be reached by one route and skipped by another.
 */
function commitOverrides(
  cleaned: Record<string, unknown>,
  options: { confirmIrreversible?: boolean } = {}
): CountryProfile {
  const base = getCountryProfile(process.env.AMRIT_COUNTRY_PROFILE || database.getPreferences().country_profile_id)
  // Validates the merged result, so the screen cannot store a profile the app rejects.
  applyOverrides(base, cleaned)

  const breaking = irreversibleChanges(storedOverrides(), cleaned)
  if (breaking.length && !options.confirmIrreversible) {
    throw new Error(
      'Changing the identifier namespace cannot be undone for data already exported: bundles ' +
      'already sent carry the previous system URIs. Confirm explicitly to proceed.'
    )
  }
  if (breaking.length) {
    const namespace = cleaned.identifier_namespace as Record<string, unknown> | undefined
    if (namespace && !namespace.effective_from) namespace.effective_from = new Date().toISOString()
  }

  database.savePreferences({ [DEPLOYMENT_OVERRIDES_KEY]: JSON.stringify(cleaned) })
  clearCountryProfileCache()
  const profile = activeCountryProfile()
  setActiveCountryProfile(profile)
  rebuildOneHealthModules()
  return profile
}

async function loadLlmConfig(): Promise<LLMServiceConfig> {
  const preferences = database.getPreferences()
  const rawProvider = (preferences.llm_provider ?? 'disabled').toLocaleLowerCase()
  const provider: LLMProvider = ['disabled', 'ollama', 'openai', 'anthropic'].includes(rawProvider)
    ? rawProvider as LLMProvider
    : 'disabled'
  return {
    provider,
    apiKey: await vault.get(LLM_KEY),
    model: preferences.llm_model ?? '',
    baseUrl: preferences.llm_base_url ?? '',
    networkEnabled: boolPreference(preferences.llm_network_enabled),
    temperature: Number(preferences.llm_temperature || 0.2),
    maxTokens: integerPreference(preferences.llm_max_tokens, 800, 32, 8192),
    redactPhi: boolPreference(preferences.llm_redact_phi, true)
  }
}

function broadcastSyncStatus(status: SyncStatus): void {
  for (const window of BrowserWindow.getAllWindows()) {
    if (!window.isDestroyed()) window.webContents.send(channels.syncStatusEvent, status)
  }
}

function registerIpc(): void {
  handle(channels.bootstrap, async (): Promise<AppBootstrap> => {
    const base = database.getBootstrapData()
    return {
      ...base,
      migratedFrom: databaseLocation.migratedFrom,
      syncStatus: { ...syncManager.getStatus(), tokenConfigured: Boolean(await vault.get(SYNC_TOKEN_KEY)) },
      appVersion: app.getVersion(),
      countryProfile: activeCountryProfile()
    }
  })

  handle(channels.countryProfileGet, async () => activeCountryProfile())

  /**
   * The ISO 3166-1 country list, from the checked-in reference the profiles are built from.
   *
   * Narrowed to name and codes on the way out. The reference entry also carries locale,
   * time zone and numbering-system defaults, which belong to profile synthesis and have no
   * business being reachable from a form.
   */
  handle(channels.countriesList, async (): Promise<CountryOption[]> =>
    availableCountries({ isoOnly: true }).map((entry) => ({
      alpha3: entry.alpha3, alpha2: entry.alpha2, name: entry.name, who_region: entry.who_region
    })))

  handle(channels.addressFormatGet, async (rawCountryCode) =>
    addressFormatFor(codeSchema.parse(rawCountryCode ?? activeCountryProfile().country_code)))

  /**
   * Placing a facility on a map. Read-only, offline, and bounded: the arguments are
   * validated here because the renderer supplies them, and the postal code is capped so a
   * pathological input cannot walk the whole prefix ladder.
   */
  handle(channels.geoPostalLookup, async (rawCountry, rawCode, rawSubdivision) =>
    lookupPostalCode(
      codeSchema.parse(rawCountry ?? activeCountryProfile().country_code),
      z.string().max(32).catch('').parse(rawCode),
      z.string().max(16).optional().catch(undefined).parse(rawSubdivision)
    ))

  handle(channels.geoLocalitySearch, async (rawCountry, rawQuery) =>
    lookupLocality(
      codeSchema.parse(rawCountry ?? activeCountryProfile().country_code),
      z.string().max(120).catch('').parse(rawQuery)
    ))

  handle(channels.geoReportingUnits, async (rawCountry) =>
    database.reportingUnits(codeSchema.parse(rawCountry ?? activeCountryProfile().country_code)))

  /**
   * Terminology search, for the diagnosis picker and anything else that has to offer a code.
   *
   * Phase 24. Bounded on purpose: the renderer supplies the arguments, so the system is checked
   * against the list this deployment actually bundles, the filter is capped, and the page size
   * is capped. `expand` reports how many matched rather than how many it returned, which is what
   * lets a picker say "showing 50 of 412" instead of implying it found fifty.
   *
   * The deployment's own licence gate applies here exactly as it does on export: a system this
   * deployment has switched off answers with the reason, not with an empty list.
   */
  handle(channels.terminologyExpand, async (rawSystem, rawFilter, rawCount) => {
    const seed = loadTerminologySeed()
    return expandTerminology(seed, {
      system: z.string().max(200).catch('').parse(rawSystem),
      filter: z.string().max(120).catch('').parse(rawFilter),
      count: z.number().int().min(1).max(500).catch(50).parse(rawCount)
    }, profileGate())
  })

  handle(channels.terminologyLookup, async (rawSystem, rawCode) =>
    lookupTerminology(
      loadTerminologySeed(),
      z.string().max(200).catch('').parse(rawSystem),
      z.string().max(64).catch('').parse(rawCode),
      profileGate()
    ))

  handle(channels.dataLicences, async () => dataLicences())

  /**
   * Deployment settings. Authorisation is enforced here in the main process: the renderer
   * cannot be trusted to gate it, and hiding a menu item is not an access control.
   */
  handle(channels.deploymentSettingsGet, async () => {
    requirePermission(oneHealthSession.current(), 'users:manage')
    return { overrides: storedOverrides(), profile: activeCountryProfile() }
  })

  handle(channels.deploymentSettingsSave, async (rawOverrides, rawOptions) => {
    requirePermission(oneHealthSession.current(), 'users:manage')
    return commitOverrides(
      validateOverrides(rawOverrides as Record<string, unknown>),
      (rawOptions ?? {}) as { confirmIrreversible?: boolean }
    )
  })

  handle(channels.deploymentSettingsCountry, async (rawCountry, rawOptions) => {
    requirePermission(oneHealthSession.current(), 'users:manage')
    if (process.env.AMRIT_COUNTRY_PROFILE) {
      throw new Error(
        'This deployment country is fixed by AMRIT_COUNTRY_PROFILE. Remove that environment override to select it here.'
      )
    }
    const options = z.object({ confirmCountryChange: z.boolean().optional() }).strict().parse(rawOptions ?? {})
    const requested = z.string().trim().min(2).max(80).parse(rawCountry)
    const current = activeCountryProfile()
    const nextBase = getCountryProfile(requested)
    if (nextBase.country_code === current.country_code) return current
    if (current.country_code !== 'ZZZ' && !options.confirmCountryChange) {
      throw new Error(
        `Changing the deployment country from ${current.country_name} to ${nextBase.country_name} ` +
        'changes address rules, administrative labels, map defaults and export identifiers. Confirm explicitly to proceed.'
      )
    }

    database.savePreferences({
      country_profile_id: nextBase.profile_id,
      [DEPLOYMENT_OVERRIDES_KEY]: '{}'
    })
    clearCountryProfileCache()
    const profile = activeCountryProfile()
    const geoPack = database.seedActiveGeoPack()
    database.recordAudit(
      'deployment.country',
      'warning',
      `${current.country_code} -> ${profile.country_code}`,
      { previousProfile: current.profile_id, nextProfile: profile.profile_id, geoPack }
    )
    return profile
  })

  handle(channels.deploymentSettingsReset, async () => {
    requirePermission(oneHealthSession.current(), 'users:manage')
    database.savePreferences({ [DEPLOYMENT_OVERRIDES_KEY]: '{}' })
    clearCountryProfileCache()
    const profile = activeCountryProfile()
    setActiveCountryProfile(profile)
    rebuildOneHealthModules()
    return profile
  })

  /**
   * Logo upload. The file is judged by its bytes, not its name or extension, and is then
   * decoded and re-encoded so the stored image is one this codebase produced — trailing
   * content after a valid header does not survive. Decoding is Chromium's, and a format it
   * declines is refused rather than stored undecoded: a guarantee is either enforced or the
   * operation fails.
   */
  handle(channels.deploymentSettingsLogo, async (rawPath) => {
    requirePermission(oneHealthSession.current(), 'users:manage')
    const path = pathSchema.parse(rawPath)
    const data = new Uint8Array(await readFile(path))
    validateLogo(data, basename(path))

    const decoded = nativeImage.createFromBuffer(Buffer.from(data))
    if (decoded.isEmpty()) {
      throw new Error(
        'That image could not be decoded, so it cannot be re-encoded and will not be stored. ' +
        'Save it as a PNG or JPEG and try again.'
      )
    }
    const { width, height } = decoded.getSize()
    if (Math.max(width, height) > MAX_LOGO_PIXELS) {
      throw new Error(`The logo is ${width}×${height}; the limit is ${MAX_LOGO_PIXELS}px on the longest side.`)
    }

    const overrides = storedOverrides()
    const branding = { ...(overrides.branding as Record<string, unknown> | undefined) }
    branding.logo = logoDataUri(decoded.toPNG(), 'image/png')
    return commitOverrides(validateOverrides({ ...overrides, branding }), { confirmIrreversible: true })
  })

  handle(channels.deploymentSettingsExport, async (rawPath) => {
    requirePermission(oneHealthSession.current(), 'users:manage')
    const destination = pathSchema.parse(rawPath)
    await writeFile(destination, `${JSON.stringify(activeCountryProfile(), null, 2)}\n`, 'utf8')
    return destination
  })

  handle(channels.deploymentSettingsImport, async (rawPath, rawOptions) => {
    requirePermission(oneHealthSession.current(), 'users:manage')
    const path = pathSchema.parse(rawPath)
    let document: unknown
    try {
      document = JSON.parse(await readFile(path, 'utf8')) as unknown
    } catch (error) {
      throw new Error(`That file is not valid JSON: ${error instanceof Error ? error.message : String(error)}`)
    }
    return commitOverrides(
      overridesFromProfile(document as Record<string, unknown>),
      (rawOptions ?? {}) as { confirmIrreversible?: boolean }
    )
  })

  handle(channels.chooseFile, async (rawOptions) => {
    const options = fileOptionsSchema.parse(rawOptions)
    const dialogOptions: OpenDialogOptions = {
      properties: ['openFile'],
      filters: options?.filters
    }
    const result = mainWindow
      ? await dialog.showOpenDialog(mainWindow, dialogOptions)
      : await dialog.showOpenDialog(dialogOptions)
    const selected = result.canceled ? null : result.filePaths[0] ?? null
    if (selected) approvedReadPaths.add(resolve(selected))
    return selected
  })
  handle(channels.chooseSave, async (rawOptions) => {
    const options = saveOptionsSchema.parse(rawOptions)
    const result = mainWindow
      ? await dialog.showSaveDialog(mainWindow, options)
      : await dialog.showSaveDialog(options)
    const selected = result.canceled ? null : result.filePath ?? null
    if (selected) approvedWritePaths.add(resolve(selected))
    return selected
  })
  handle(channels.openExternal, async (rawUrl) => {
    const url = assertHttpUrl(z.string().url().max(2_000).parse(rawUrl), true)
    await shell.openExternal(url.href)
  })

  handle(channels.labsList, () => database.listLabs())
  handle(channels.labsSave, (rawLab) => database.saveLab(laboratorySchema.parse(rawLab)))
  handle(channels.labsClone, (rawSourceCode, rawTargetLab) =>
    database.cloneLab(codeSchema.parse(rawSourceCode), laboratorySchema.parse(rawTargetLab)))
  handle(channels.labsDelete, (rawCode) => database.deleteLab(codeSchema.parse(rawCode)))
  handle(channels.labsSelect, (rawCode) => database.selectLab(codeSchema.parse(rawCode)))

  handle(channels.masterDefinitions, () => database.masterDefinitions())
  handle(channels.masterList, (rawKind, rawOptions) => {
    const kind = masterKindSchema.parse(rawKind)
    // The cap is a denial-of-service guard, not a business rule, so it has to clear the
    // largest catalogue a real deployment holds. Administrative units are that catalogue:
    // a country importing districts and sub-districts runs to tens of thousands, and at
    // 10 000 the laboratory editor's unit picker failed outright rather than truncating.
    const options = z.object({ labCode: codeSchema.optional(), query: z.string().max(500).optional(), includeInactive: z.boolean().optional(), limit: z.number().int().min(1).max(200_000).optional() }).strict().optional().parse(rawOptions)
    return database.listMaster(kind, options)
  })
  handle(channels.masterSave, (rawKind, rawRow, rawLabCode) =>
    database.saveMaster(masterKindSchema.parse(rawKind), rowSchema.parse(rawRow) as Row, rawLabCode ? codeSchema.parse(rawLabCode) : undefined))
  handle(channels.masterDelete, (rawKind, rawKey, rawLabCode) =>
    database.deleteMaster(masterKindSchema.parse(rawKind), scalarKeySchema.parse(rawKey), rawLabCode ? codeSchema.parse(rawLabCode) : undefined))
  handle(channels.masterToggle, (rawKind, rawKey, rawActive, rawLabCode) =>
    database.toggleMaster(masterKindSchema.parse(rawKind), scalarKeySchema.parse(rawKey), z.boolean().parse(rawActive), rawLabCode ? codeSchema.parse(rawLabCode) : undefined))

  handle(channels.recordsList, (rawFilters) => database.listRecords(filtersSchema.parse(rawFilters ?? {})))
  handle(channels.recordsGet, (rawId) => database.getRecord(idSchema.parse(rawId)))
  handle(channels.recordsSave, (rawRecord) => database.saveRecord(recordSchema.parse(rawRecord) as unknown as IsolateRecord))
  handle(channels.recordsDelete, (rawId) => database.deleteRecord(idSchema.parse(rawId)))
  handle(channels.recordsDuplicate, (rawRecord) => database.findDuplicate(recordSchema.parse(rawRecord) as unknown as IsolateRecord))
  handle(channels.panelsMatch, (rawContext) => database.matchPanels(filtersSchema.parse(rawContext ?? {})))

  handle(channels.omicsList, (rawId) => database.listOmics(idSchema.parse(rawId)))
  handle(channels.omicsAttach, async (rawId, rawPath, rawOptions) => {
    const isolateId = idSchema.parse(rawId)
    const record = database.getRecord(isolateId)
    if (!record) throw new Error(`Unknown isolate record: ${isolateId}`)
    const options = z.object({ copy: z.boolean().optional() }).strict().optional().parse(rawOptions ?? undefined)
    return attachOmicsFile(approvedPath(rawPath, 'read'), {
      workspace: app.getPath('userData'), labCode: String(record.lab_code ?? ''), isolateId, copy: options?.copy
    })
  })
  handle(channels.omicsSave, (rawEntry) => database.saveOmics(rowSchema.parse(rawEntry) as Record<string, unknown>))
  handle(channels.omicsDelete, async (rawId) => {
    const { storedPath } = database.deleteOmics(idSchema.parse(rawId))
    await removeStoredOmicsFile(storedPath, app.getPath('userData'))
  })
  handle(channels.omicsReveal, (rawId) => {
    const entry = database.omicsEntry(idSchema.parse(rawId))
    const target = String(entry.stored_path || entry.source_path || '')
    if (!target) throw new Error('This omics record has no file on disk; it references an accession only.')
    shell.showItemInFolder(resolve(target))
  })

  handle(channels.importPreview, (rawPath, rawLabCode, rawMapping, rawOptions) => {
    const labCode = codeSchema.parse(rawLabCode)
    const options = z.object({
      delimiter: z.string().max(10).optional(),
      defaults: z.record(z.string().max(200), z.string().max(2_000)).optional()
    }).strict().optional().parse(rawOptions) ?? {}
    return parseImportPreview(
      approvedPath(rawPath, 'read'),
      labCode,
      z.record(z.string().max(500), z.string().max(500)).optional().parse(rawMapping) ?? {},
      { ...options, validateRow: (row) => database.validateImportedRow(row, labCode) }
    )
  })
  handle(channels.importCommit, (rawPreview, rawLabCode) => {
    const preview = importPreviewSchema.parse(rawPreview)
    if (preview.errorCount) throw new Error('Resolve import errors before commit.')
    const result = database.commitImport(preview as unknown as ImportPreview, codeSchema.parse(rawLabCode))
    if (result.rolledBack) throw new Error(result.errors.map((item) => `row ${item.row}: ${item.error}`).join('; '))
    return { imported: result.imported, drafts: result.drafts }
  })
  handle(channels.importTemplate, async (rawPath, rawLabCode) => {
    const labCode = codeSchema.parse(rawLabCode)
    const antibioticRows = database.listMaster('antibiotics', { includeInactive: false, limit: 10_000 })
    const antibiotics = antibioticRows.map((row) => String(row.code ?? '')).filter(Boolean)
    const references = {
      antibiotics: antibioticRows.map((row) => ({ code: String(row.code ?? ''), name: String(row.name ?? row.code ?? '') })).filter((row) => row.code),
      organisms: database.listMaster('organisms', { includeInactive: false, limit: 10_000 })
        .map((row) => ({ code: String(row.code ?? ''), name: String(row.organism_name ?? row.code ?? '') })).filter((row) => row.code),
      samples: database.listMaster('samples', { includeInactive: false, limit: 10_000 })
        .map((row) => ({ code: String(row.code ?? ''), name: String(row.name ?? row.code ?? '') })).filter((row) => row.code),
      locations: database.listMaster('locations', { labCode, includeInactive: false, limit: 10_000 })
        .map((row) => ({ code: String(row.location_code ?? ''), name: String(row.location_name ?? row.location_code ?? '') })).filter((row) => row.code)
    }
    return createImportTemplate(approvedPath(rawPath, 'write'), labCode, antibiotics, references)
  })
  handle(channels.importProfiles, (rawLabCode) => database.listImportProfiles(codeSchema.parse(rawLabCode)))
  handle(channels.importProfileSave, (rawProfile) => database.saveImportProfile(importProfileSchema.parse(rawProfile) as ImportProfile))
  handle(channels.importProfileDelete, (rawId) => database.deleteImportProfile(idSchema.parse(rawId)))
  handle(channels.importHistory, (rawLabCode) => database.listImportHistory(codeSchema.parse(rawLabCode)))

  handle(channels.analysisRun, (rawFilters) => database.runAnalysis(analysisFiltersSchema.parse(rawFilters)))
  handle(channels.analysisMacros, (rawLabCode) => database.listAnalysisMacros(codeSchema.parse(rawLabCode)))
  handle(channels.analysisMacroSave, (rawLabCode, rawMacro) => database.saveAnalysisMacro(codeSchema.parse(rawLabCode), rowSchema.parse(rawMacro) as Row))
  handle(channels.analysisMacroDelete, (rawId) => database.deleteAnalysisMacro(idSchema.parse(rawId)))

  handle(channels.exportData, async (rawFormat, rawFilters, rawPath) => {
    const format = z.enum(['whonet', 'fhir', 'hl7', 'measure', 'json', 'csv']).parse(rawFormat)
    const filters = analysisFiltersSchema.parse(rawFilters)
    const lab = database.getLab(filters.labCode)
    if (!lab) throw new Error(`Unknown laboratory: ${filters.labCode}`)
    const rows: IsolateRecord[] = filters.recordId
      ? [database.getRecord(filters.recordId)].filter((row): row is IsolateRecord => row !== null)
      : database.listRecords({ ...filters, labCode: filters.labCode, all: true })
    const content = createExport(format, rows, lab, { antibioticCode: filters.antibioticCode, periodStart: filters.periodStart, periodEnd: filters.periodEnd })
    const destination = approvedPath(rawPath, 'write')
    await writeFile(destination, content, 'utf8')
    database.recordAudit(`export.${format}`, 'ok', `${rows.length} record(s) exported`, { destination: basename(destination), labCode: lab.code })
    return destination
  })

  handle(channels.breakpointImport, (rawPath, rawSource) =>
    importBreakpointWorkbook(approvedPath(rawPath, 'read'), sourceSchema.parse(rawSource), database))
  handle(channels.breakpointDownload, async (rawUrl) => {
    const requested = rawUrl ? z.string().url().max(2_000).parse(rawUrl) : OFFICIAL_BREAKPOINT_URLS.toolkitPartB
    const extension = extname(new URL(requested).pathname) || '.xlsb'
    const suggested = basename(new URL(requested).pathname) || `CLSI-breakpoints${extension}`
    const breakpointOptions = {
      defaultPath: suggested,
      filters: [{ name: 'Breakpoint workbook', extensions: [extension.replace('.', '')] }]
    }
    const choice = mainWindow
      ? await dialog.showSaveDialog(mainWindow, breakpointOptions)
      : await dialog.showSaveDialog(breakpointOptions)
    if (choice.canceled || !choice.filePath) throw new Error('Download cancelled.')
    approvedWritePaths.add(resolve(choice.filePath))
    await downloadOfficialBreakpointFile(requested, choice.filePath)
    database.recordAudit('breakpoints.download', 'ok', `Official workbook downloaded: ${basename(choice.filePath)}`, { url: requested })
    return { path: choice.filePath }
  })
  handle(channels.breakpointSets, () => database.listBreakpointSets())
  handle(channels.breakpointActivate, (rawId) => database.activateBreakpointSet(idSchema.parse(rawId)))

  /**
   * One-button EUCAST update. Takes no argument on purpose: the URL is the allowlisted
   * eucast.org path built from a known edition, so nothing the renderer says can point this
   * at another host. The set is staged inactive like any other import; activation stays a
   * separate, explicit act with its own validation gate.
   */
  handle(channels.breakpointEucastUpdate, async () => {
    const result = await updateEucastBreakpoints({ repository: database, bundledPath: eucastBundledPath() })
    database.recordAudit('breakpoints.eucast-update', 'ok',
      `${result.imported} EUCAST row(s) staged from ${result.origin} (${result.edition || 'unknown edition'})`,
      { origin: result.origin, sourceHash: result.sourceHash })
    return result
  })
  handle(channels.breakpointEucastStatus, async () => {
    const sets = database.listBreakpointSets()
    const eucast = sets.find((row) => String(row.organization ?? '').toUpperCase() === 'EUCAST')
    let bundled: string | null = null
    try {
      const raw = JSON.parse(await readFile(eucastBundledPath(), 'utf8')) as { version?: string }
      bundled = String(raw.version ?? '') || null
    } catch { bundled = null }
    return {
      installed: eucast ? String(eucast.edition ?? eucast.year ?? '') || null : null,
      installedRows: eucast ? Number(eucast.breakpoint_count ?? 0) : 0,
      bundled,
      sourceUrl: BREAKPOINT_SOURCES.EUCAST.links.toolkit,
      licence: BREAKPOINT_SOURCES.EUCAST.licence
    }
  })

  handle(channels.syncGet, async () => ({
    config: await rendererSyncConfig(),
    status: { ...syncManager.getStatus(), tokenConfigured: Boolean(await vault.get(SYNC_TOKEN_KEY)) }
  }))
  handle(channels.syncSave, async (rawConfig) => {
    const saved = await saveSyncConfig(rawConfig as SyncConfig)
    return { ...saved, authToken: '', siteToken: '', pickupToken: '' }
  })
  handle(channels.syncStart, async (rawConfig) => {
    const config = rawConfig ? await saveSyncConfig(rawConfig as SyncConfig) : syncConfigSchema.parse(await loadSyncConfig())
    return syncManager.start(config)
  })
  handle(channels.syncStop, () => syncManager.stop())
  handle(channels.syncTest, async (rawConfig) => {
    const config = rawConfig ? await saveSyncConfig(rawConfig as SyncConfig) : syncConfigSchema.parse(await loadSyncConfig())
    return syncManager.test(config)
  })
  handle(channels.syncConfigureToken, async (rawConfig) => {
    const config = rawConfig ? await saveSyncConfig(rawConfig as SyncConfig) : syncConfigSchema.parse(await loadSyncConfig())
    const configured = await syncManager.configureToken(config, true)
    enrolmentController?.abort()
    await vault.set(SYNC_TOKEN_KEY, configured.authToken)
    await vault.remove(PICKUP_TOKEN_KEY)
    database.savePreferences({ sync_pickup_expires_at: '' })
    database.recordAudit('sync.token.collect', 'warning', 'A bearer token was collected from the central server and encrypted.')
    return { ...configured, authToken: '', siteToken: '', pickupToken: '' }
  })
  handle(channels.syncRequestAccess, async (rawConfig) => {
    // Asking to join is recorded locally whatever the answer: an installation that requested
    // access and heard nothing is a thing an auditor should be able to see afterwards.
    const config = rawConfig ? await saveSyncConfig(rawConfig as SyncConfig) : syncConfigSchema.parse(await loadSyncConfig())
    const lab = database.currentLab()
    const text = (value: unknown): string => (value === undefined || value === null ? '' : String(value)).trim()
    // Sent as codes at their depth rather than as level names, so the same request shape works
    // for a country with one sub-national level and one with five. admin_path is
    // "<country>/<code>/<code>…", so a segment's position past the country *is* its level; the
    // server resolves the deepest one it recognises when the request is approved.
    const pathSegments = text(lab?.admin_path).split('/').filter(Boolean).slice(1)
    const result = await syncManager.requestAccess(config, {
      name: text(lab?.name) || config.labCode,
      country: text(lab?.country),
      country_code: text(lab?.country_code),
      contact_email: text(lab?.contact_email),
      app_version: app.getVersion(),
      admin_units: pathSegments.map((code, index) => ({ level: index + 1, code })),
      address: (lab?.address ?? undefined) as Record<string, unknown> | undefined
    })
    if (result.status === 'pending') {
      // Registration of an unknown/deleted site means any bearer retained from an older
      // approval is invalid. Remove it before polling so it cannot masquerade as the token
      // that the pending request has not received yet.
      await vault.remove(SYNC_TOKEN_KEY)
      broadcastSyncStatus({ ...syncManager.getStatus(), tokenConfigured: false, lastError: '' })
    }
    if (result.pickupToken) await vault.set(PICKUP_TOKEN_KEY, result.pickupToken)
    if (result.pickupToken) {
      database.savePreferences({ sync_pickup_expires_at: result.pickupExpiresAt })
      beginAccessTokenCollection(
        { ...config, authToken: '', pickupToken: result.pickupToken },
        result.intervalSeconds,
        result.pickupExpiresAt
      )
    }
    database.recordAudit(
      'sync.access.request',
      result.status === 'pending' ? 'warning' : 'ok',
      `Registration ${result.status === 'pending' ? 'requested for' : 'confirmed for'} ${config.labCode}: ${result.detail}`
    )
    // The pickup token itself never crosses back to the renderer.
    return { status: result.status, detail: result.detail, requestedAt: result.requestedAt }
  })

  /**
   * Open the operating system's location-privacy settings.
   *
   * When location services are switched off, or this application has been refused them,
   * nothing in here can turn them back on: that decision belongs to the operating system
   * and to the person at the keyboard. The most this can do is take them to the screen
   * where the switch is, and say so plainly when it does not know where that screen is.
   */
  handle(channels.syncOpenLocationSettings, async () => {
    const targets: Record<string, string> = {
      darwin: 'x-apple.systempreferences:com.apple.preference.security?Privacy_LocationServices',
      win32: 'ms-settings:privacy-location'
    }
    const target = targets[process.platform]
    if (!target) {
      return {
        opened: false,
        detail: 'Open your desktop environment\'s location or privacy settings to allow this application to read the computer\'s location, then try again. Coordinates can also be typed in by hand.'
      }
    }
    try {
      await shell.openExternal(target)
      return { opened: true, detail: 'Allow location for this application, then use “Use this computer’s location” again.' }
    } catch (error) {
      return { opened: false, detail: errorMessage(error) }
    }
  })

  /**
   * What this build can expect from the computer's own location service, and why.
   *
   * Chromium answers a failed fix with "position unavailable" whatever the cause, which is
   * useless to somebody trying to fix it. The causes differ by platform and by how the
   * application was built, and the main process is the only place that knows both:
   *
   * - macOS reads Core Location, but only for a bundle whose Info.plist asks for it. That
   *   entry belongs to the packaged application, so a development build is refused before
   *   the operating system is ever consulted — nothing the operator does will change it.
   * - Windows and Linux fall back to Chromium's network provider, which needs a Google API
   *   key this project does not ship, so it answers nothing.
   *
   * In every one of those cases the coordinates are still typeable, which is why none of
   * this is fatal — but the screen should say which case it is.
   */
  handle(channels.syncLocationSupport, () => {
    const packaged = app.isPackaged
    if (process.platform === 'darwin') {
      return packaged
        ? { platform: 'darwin', packaged, supported: true, detail: '' }
        : {
            platform: 'darwin', packaged, supported: false,
            detail: 'This is a development build. macOS only reads a location for the packaged application, whose bundle declares why it wants one, so reading this computer’s location will not work here. Type the coordinates in below, or try again from an installed build.'
          }
    }
    return {
      platform: process.platform, packaged, supported: false,
      detail: 'This build has no location provider: Windows and Linux use a network location service that AMRIT does not ship a key for. Type the coordinates in below — a laboratory’s position does not change, so entering it once is enough.'
    }
  })

  handle(channels.auditList, (rawLimit) => database.listAudit(rawLimit === undefined ? 200 : z.number().int().min(1).max(10_000).parse(rawLimit)))
  handle(channels.preferencesGet, async () => {
    const values = Object.fromEntries(Object.entries(database.getPreferences()).filter(([key]) => !SECRET_PREFERENCE_KEYS.has(key)))
    values.sync_auth_token_configured = (await vault.get(SYNC_TOKEN_KEY)) ? '1' : '0'
    values.sync_site_token_configured = (await vault.get(SITE_TOKEN_KEY)) ? '1' : '0'
    values.llm_api_key_configured = (await vault.get(LLM_KEY)) ? '1' : '0'
    values.credential_persistence = vault.canPersist() ? 'os-encrypted' : 'memory-only'
    values['llm.provider'] = values.llm_provider ?? 'disabled'
    values['llm.endpoint'] = values.llm_base_url ?? ''
    values['llm.model'] = values.llm_model ?? ''
    values['llm.enabled'] = values.llm_network_enabled ?? '0'
    values['llm.externalOptIn'] = values.llm_external_opt_in ?? '0'
    values['llm.redactIdentifiers'] = values.llm_redact_phi ?? '1'
    return values
  })
  handle(channels.preferencesSave, async (rawValues) => {
    const values = preferencesSchema.parse(rawValues)
    const authToken = values.sync_auth_token || values['sync.authToken']
    const siteToken = values.sync_site_token || values['sync.siteToken']
    const llmKey = values.llm_api_key || values['llm.apiKey']
    if (authToken) await vault.set(SYNC_TOKEN_KEY, authToken)
    if (siteToken) await vault.set(SITE_TOKEN_KEY, siteToken)
    if (boolPreference(values.llm_api_key_clear)) {
      await vault.remove(LLM_KEY)
      database.recordAudit('security.secret-clear', 'warning', 'Stored AI provider credential removed from the encrypted vault.')
    } else if (llmKey) await vault.set(LLM_KEY, llmKey)
    const safeValues = Object.fromEntries(Object.entries(values).filter(([key]) =>
      !SECRET_PREFERENCE_KEYS.has(key) && key !== 'llm_api_key_clear' && !key.endsWith('_configured') && !key.startsWith('llm.')))
    if (values['llm.provider'] !== undefined) safeValues.llm_provider = values['llm.provider']
    if (values['llm.endpoint'] !== undefined) safeValues.llm_base_url = values['llm.endpoint']
    if (values['llm.model'] !== undefined) safeValues.llm_model = values['llm.model']
    if (values['llm.redactIdentifiers'] !== undefined) safeValues.llm_redact_phi = boolPreference(values['llm.redactIdentifiers']) ? '1' : '0'
    if (values['llm.externalOptIn'] !== undefined) safeValues.llm_external_opt_in = boolPreference(values['llm.externalOptIn']) ? '1' : '0'
    if (values['llm.enabled'] !== undefined) {
      const provider = values['llm.provider'] || database.getPreferences().llm_provider || 'disabled'
      const enabled = boolPreference(values['llm.enabled'])
      const optedIn = provider === 'ollama' || boolPreference(values['llm.externalOptIn'])
      safeValues.llm_network_enabled = enabled && optedIn ? '1' : '0'
    }
    database.savePreferences({ ...safeValues, sync_auth_token: '', sync_site_token: '', llm_api_key: '' })
  })

  handle(channels.llmAsk, async (rawTemplate, rawFields) => {
    const requestedTemplate = z.string().min(1).max(20_000).parse(rawTemplate)
    const aliases: Record<string, string> = { freeform: 'free', amr_summary: 'trend_narrative', data_quality: 'free', interpretive_comment: 'free', one_health: 'free' }
    const template = aliases[requestedTemplate] ?? requestedTemplate
    const parsedFields = z.record(z.string().max(200), z.string().max(50_000)).parse(rawFields)
    const fields = { ...parsedFields, text: parsedFields.text || parsedFields.question || '', summary: parsedFields.summary || parsedFields.question || '' }
    return askLLM(await loadLlmConfig(), template, fields)
  })
  handle(channels.llmModels, async () => {
    const config = await loadLlmConfig()
    return listLocalModels(config.baseUrl, config.networkEnabled)
  })
  handle(channels.llmPull, async (rawModel) => {
    const config = await loadLlmConfig()
    await pullLocalModel(modelNameSchema.parse(rawModel), config.baseUrl, config.networkEnabled)
  })
  handle(channels.llmDelete, async (rawModel) => {
    const config = await loadLlmConfig()
    await deleteLocalModel(modelNameSchema.parse(rawModel), config.baseUrl, config.networkEnabled)
  })
  handle(channels.llmTest, async () => testLLM(await loadLlmConfig()))

  const oneHealthStatus = (): ReturnType<OneHealthSession['status']> & { needsBootstrap: boolean } => ({
    needsBootstrap: !database.hasOneHealthUsers(),
    ...oneHealthSession.status()
  })
  handle(channels.oneHealthAuthStatus, () => oneHealthStatus())
  handle(channels.oneHealthBootstrapAdmin, (rawUsername, rawPassword) => {
    const username = oneHealthUsernameSchema.parse(rawUsername)
    const password = oneHealthNewPasswordSchema.parse(rawPassword)
    oneHealthSession.establish(database.bootstrapOneHealthAdmin(username, password))
    return oneHealthStatus()
  })
  handle(channels.oneHealthLogin, (rawUsername, rawPassword) => {
    const username = oneHealthUsernameSchema.parse(rawUsername)
    const password = oneHealthPasswordSchema.parse(rawPassword)
    const identity = database.authenticateOneHealth(username, password)
    if (!identity) throw new Error('Invalid username or password.')
    oneHealthSession.establish(identity)
    return oneHealthStatus()
  })
  handle(channels.oneHealthLogout, () => {
    oneHealthSession.clear()
    return oneHealthStatus()
  })
  handle(channels.oneHealthUsers, () => database.listOneHealthUsers(oneHealthSession.current()))
  handle(channels.oneHealthUserCreate, (rawInput) => {
    const input = z.object({
      username: oneHealthUsernameSchema,
      password: oneHealthNewPasswordSchema,
      roles: z.array(oneHealthRoleSchema).min(1).max(6)
    }).strict().parse(rawInput)
    return database.createOneHealthUser(input, oneHealthSession.current())
  })
  handle(channels.oneHealthModules, () => database.oneHealthModules())
  handle(channels.oneHealthCapture, (rawModule, rawPayload) =>
    database.captureOneHealth(
      moduleKeySchema.parse(rawModule),
      rowSchema.parse(rawPayload) as Row,
      oneHealthSession.current()
    ))
  handle(channels.oneHealthRecords, (rawModule) => {
    const identity = oneHealthSession.current()
    requirePermission(identity, 'event:read')
    return database.listOneHealth(rawModule ? moduleKeySchema.parse(rawModule) : undefined)
  })
  handle(channels.oneHealthMetrics, (rawModule) => {
    const identity = oneHealthSession.current()
    requirePermission(identity, 'metrics:read')
    return database.oneHealthMetrics(moduleKeySchema.parse(rawModule))
  })
  handle(channels.oneHealthEnqueue, (rawModule) =>
    database.enqueueOneHealth(moduleKeySchema.parse(rawModule), oneHealthSession.current()))
  handle(channels.oneHealthExport, async (rawFormat, rawModule, rawPath) => {
    const format = oneHealthExportSchema.parse(rawFormat) as OneHealthExportFormat
    const module = moduleKeySchema.parse(rawModule)
    const destination = approvedPath(rawPath, 'write')
    const identity = oneHealthSession.current()
    let payload: Record<string, unknown>
    if (format === 'aggregate') {
      requirePermission(identity, 'metrics:read')
      payload = database.oneHealthAggregate(module)
    } else {
      requirePermission(identity, 'event:read')
      if (format === 'glass') payload = glassProduct(database.listOneHealthForExport(module))
      else if (format === 'animuse') {
        if (module !== 'veterinary') throw new Error('WOAH ANIMUSE projection is available for the veterinary module.')
        payload = animuseProduct(database.listOneHealthForExport('veterinary'))
      } else payload = infarmProduct(database.listOneHealthForExport('veterinary'), database.listOneHealthForExport('food'))
    }
    await writeFile(destination, JSON.stringify(payload, null, 2), 'utf8')
    database.recordAudit('one-health.export', 'ok', `${format}: ${module}`, {
      destination: basename(destination), profile: String(payload.profile ?? payload.contract ?? format)
    }, identity.username)
    return destination
  })
  handle(channels.oneHealthBackup, async (rawPath) => {
    const identity = oneHealthSession.current()
    requirePermission(identity, 'users:manage')
    return database.backupTo(approvedPath(rawPath, 'write'))
  })
  handle(channels.oneHealthAlerts, (rawModule) => {
    const identity = oneHealthSession.current()
    requirePermission(identity, 'event:read')
    return database.listOneHealthAlerts(rawModule ? moduleKeySchema.parse(rawModule) : undefined)
  })
  handle(channels.oneHealthAlertReview, (rawId, rawInput) => {
    const input = z.object({ status: oneHealthReviewStatusSchema, note: z.string().max(4_000).optional() }).strict().parse(rawInput)
    return database.reviewOneHealthAlert(z.string().uuid().parse(rawId), input, oneHealthSession.current())
  })
  handle(channels.oneHealthActions, (rawModule) =>
    database.listOneHealthActions(rawModule ? moduleKeySchema.parse(rawModule) : undefined, oneHealthSession.current()))
  handle(channels.oneHealthActionCreate, (rawInput) => {
    const input = z.object({
      event_id: z.string().uuid().optional(), title: z.string().trim().min(1).max(500),
      owner: z.string().trim().max(200).optional(), due_at: z.string().max(100).optional(),
      priority: z.enum(['low', 'medium', 'high', 'critical']).optional(), evidence: z.string().max(4_000).optional()
    }).strict().parse(rawInput)
    return database.createOneHealthAction(input as Row, oneHealthSession.current())
  })
  handle(channels.oneHealthActionUpdate, (rawId, rawInput) => {
    const input = z.object({ status: oneHealthActionStatusSchema, evidence: z.string().max(4_000).optional() }).strict().parse(rawInput)
    return database.updateOneHealthAction(z.string().uuid().parse(rawId), input, oneHealthSession.current())
  })
  handle(channels.oneHealthAudit, (rawLimit) => database.listOneHealthAudit(
    oneHealthSession.current(), rawLimit === undefined ? 500 : z.number().int().min(1).max(10_000).parse(rawLimit)
  ))
  handle(channels.oneHealthAuditVerify, () => database.verifyOneHealthAuditChain(oneHealthSession.current()))
  handle(channels.oneHealthOutbox, () => {
    const identity = oneHealthSession.current()
    requirePermission(identity, 'exchange:read')
    return database.listOneHealthOutbox()
  })

  /**
   * Retention and erasure. Both are irreversible, so both re-check authorisation here and
   * default to the safe direction: a purge is a dry run unless the caller asks otherwise.
   */
  handle(channels.privacyRetentionPurge, (rawOptions) => {
    const options = (rawOptions ?? {}) as { dryRun?: boolean }
    return database.purgeExpiredData(oneHealthSession.current(), { dryRun: options.dryRun !== false })
  })

  handle(channels.privacyAuditErase, (rawType, rawId, rawReason) => {
    const objectType = z.string().trim().min(1).max(200).parse(rawType)
    const objectId = z.string().trim().min(1).max(200).parse(rawId)
    const reason = z.string().trim().min(1).max(2_000).parse(rawReason)
    return database.eraseAuditDetails(oneHealthSession.current(), objectType, objectId, reason)
  })
}

/**
 * The screen the window opens on.
 *
 * The renderer already routes from the URL hash, so this only needs to set one. It exists
 * for support and for documentation capture — "open the app on the imports screen" — and is
 * validated against nothing but the character set, because an unknown route falls back to
 * the dashboard in the renderer anyway.
 */
function startRouteHash(): string | undefined {
  const route = String(process.env.AMRIT_START_ROUTE || '').replace(/[^A-Za-z]/g, '')
  return route ? `/${route}` : undefined
}

function createWindow(): void {
  // The window title is the deployment's product name, not this codebase's. A build shipped
  // to another country showed "ICMR AMRIT" in the window bar and in the app switcher.
  const branding = activeCountryProfile().branding
  mainWindow = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 1040,
    minHeight: 680,
    show: false,
    backgroundColor: '#F4F7FB',
    title: branding?.product_name || 'AMRIT',
    webPreferences: {
      preload: join(currentDirectory, '../preload/index.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
      spellcheck: true
    }
  })
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    try {
      const parsed = assertHttpUrl(url, true)
      void shell.openExternal(parsed.href)
    } catch { /* deny invalid destinations */ }
    return { action: 'deny' }
  })
  mainWindow.webContents.on('will-navigate', (event) => event.preventDefault())
  mainWindow.once('ready-to-show', () => {
    mainWindow?.show()
    const captureDirectory = process.env.AMRIT_CAPTURE_DIR
    if (captureDirectory && !app.isPackaged && mainWindow) void captureScreens(mainWindow, captureDirectory)
  })
  mainWindow.on('closed', () => { mainWindow = null })
  const hash = startRouteHash()
  if (process.env.ELECTRON_RENDERER_URL) {
    void mainWindow.loadURL(`${process.env.ELECTRON_RENDERER_URL}${hash ? `#${hash}` : ''}`)
  } else {
    void mainWindow.loadFile(join(currentDirectory, '../renderer/index.html'), hash ? { hash } : undefined)
  }
}

/**
 * Write one PNG per screen, then quit.
 *
 * Documentation capture, for the manual: the alternative is screenshotting the desktop,
 * which needs accessibility permission, catches whatever else is on screen, and drifts the
 * moment a screen changes. This renders the real application against the real database and
 * is reproducible on any machine. Development builds only — a packaged application never
 * takes screenshots of itself.
 */
async function captureScreens(window: BrowserWindow, directory: string): Promise<void> {
  const routes = [
    'dashboard', 'laboratories', 'records', 'imports', 'analytics', 'exports',
    'masters', 'breakpoints', 'oneHealth', 'sync', 'ai', 'deployment', 'audit'
  ]
  /**
   * Screens whose real content is behind the page's primary action, captured a second time
   * with that action taken. The address form is the clearest example: the laboratory list
   * shows a rendered address, but only the editor shows which fields a country is asked
   * for — and that form is what changes when the deployment's country changes.
   */
  const editors: Array<[route: string, name: string, selector: string]> = [
    // The empty form: which fields this country asks for at all.
    ['laboratories', 'laboratory-editor', '.page-header__actions button'],
    // An existing facility: the same form with an address in it, so the manual shows the
    // postal lookup and the resolved coordinate rather than an empty shell.
    ['laboratories', 'laboratory-editor-resolved', '.row-actions button:nth-of-type(2)']
  ]
  const settle = (milliseconds: number): Promise<void> => new Promise((done) => setTimeout(done, milliseconds))
  await settle(2500)
  // The governed screens are behind a One Health sign-in, which is the point of them; the
  // demo operator signs in here so the manual can show what they look like in use.
  if (process.env.AMRIT_DEMO_SEED) {
    await window.webContents.executeJavaScript(
      `window.amrit.oneHealth.login(${JSON.stringify(DEMO_ONE_HEALTH_ADMIN.username)}, ${JSON.stringify(DEMO_ONE_HEALTH_ADMIN.password)}).catch(() => undefined)`
    )
    await settle(800)
    // A screen photographed before its feature has been used shows an empty state, and the
    // manual then documents an application nobody has ever set up. The Breakpoint Centre is
    // the clearest case: without a staged set it shows the invitation to fetch one rather
    // than the fetch, the staging report and the rows it produced.
    console.log('staging EUCAST breakpoints for the capture…')
    const staged = await window.webContents.executeJavaScript(
      `window.amrit.breakpoints.updateEucast().then((result) => `
      + `\`\${result.origin}: \${result.imported} row(s), edition \${result.edition}\`).catch((error) => \`failed: \${error?.message ?? error}\`)`
    )
    console.log(`  ${String(staged)}`)
    await settle(1200)
  }
  for (const route of routes) {
    await window.webContents.executeJavaScript(`window.location.hash = '#/${route}'`)
    // Each screen loads its own data over IPC; capturing sooner catches a spinner.
    await settle(1800)
    const image = await window.webContents.capturePage()
    await writeFile(join(directory, `app-${route}.png`), image.toPNG())
    console.log(`captured ${route}`)
  }
  /**
   * Screens that are empty until their primary action is run.
   *
   * An analytics page with no analysis on it, or a records page with no record open, tells
   * a reader nothing about what the screen is for. Each of these is driven exactly as an
   * operator would drive it, then captured.
   */
  const actioned: Array<[route: string, name: string, script: string, wait: number]> = [
    ['analytics', 'analytics-results',
      `(() => { const button = [...document.querySelectorAll('button')].find((item) => /run analysis/i.test(item.textContent || '')); if (!button) return false; button.click(); return true })()`, 3200],
    ['records', 'records-editor',
      `(() => { const button = document.querySelector('.row-actions button'); if (!button) return false; button.click(); return true })()`, 2400],
    ['breakpoints', 'breakpoints-staged',
      `(() => { const heading = [...document.querySelectorAll('h2, h3')].find((item) => /breakpoint master preview/i.test(item.textContent || '')); heading?.scrollIntoView({ block: 'start' }); return true })()`, 1600]
  ]
  for (const [route, name, script, wait] of actioned) {
    await window.webContents.executeJavaScript(`window.location.hash = '#/${route}'`)
    await settle(1600)
    const ran = await window.webContents.executeJavaScript(script)
    if (!ran) { console.log(`skipped ${name}: the screen did not offer its action`); continue }
    await settle(wait)
    const image = await window.webContents.capturePage()
    await writeFile(join(directory, `app-${name}.png`), image.toPNG())
    console.log(`captured ${name}`)
  }
  for (const [route, name, selector] of editors) {
    await window.webContents.executeJavaScript(`window.location.hash = '#/${route}'`)
    await settle(1500)
    // Nothing is typed into the form: whatever is already on the row is what appears.
    const opened = await window.webContents.executeJavaScript(
      `(() => { const button = document.querySelector(${JSON.stringify(selector)}); if (!button) return false; button.click(); return true })()`
    )
    if (!opened) { console.log(`skipped ${name}: nothing matched ${selector}`); continue }
    // Long enough for the geographic directory to answer over IPC and the form to settle.
    await settle(2200)
    const image = await window.webContents.capturePage()
    await writeFile(join(directory, `app-${name}.png`), image.toPNG())
    console.log(`captured ${name}`)
  }
  app.quit()
}

function installApplicationMenu(): void {
  const template: MenuItemConstructorOptions[] = []
  if (process.platform === 'darwin') {
    template.push({
      label: app.name,
      submenu: [{ role: 'about' }, { type: 'separator' }, { role: 'services' }, { type: 'separator' }, { role: 'hide' }, { role: 'hideOthers' }, { role: 'unhide' }, { type: 'separator' }, { role: 'quit' }]
    })
  }
  template.push(
    {
      label: 'Edit',
      submenu: [{ role: 'undo' }, { role: 'redo' }, { type: 'separator' }, { role: 'cut' }, { role: 'copy' }, { role: 'paste' }, { role: 'selectAll' }]
    },
    {
      label: 'View',
      submenu: [{ role: 'resetZoom' }, { role: 'zoomIn' }, { role: 'zoomOut' }, { type: 'separator' }, { role: 'togglefullscreen' }]
    },
    {
      label: 'Help',
      submenu: [
        // One entry per guideline body this deployment offers. A EUCAST-only country no
        // longer sees three links to a standard it does not use and cannot obtain free.
        ...availableBreakpointSources().flatMap((key) => {
          const source = breakpointSource(key)
          return [{
            label: `${source.label} clinical breakpoints`,
            click: () => { void shell.openExternal(source.links.toolkit) }
          }]
        })
      ]
    }
  )
  Menu.setApplicationMenu(Menu.buildFromTemplate(template))
}

async function initialize(): Promise<void> {
  databaseLocation = await resolveDatabaseLocation()
  database = new AMRITDatabase(databaseLocation.path, { seedCatalog: true }).initialize()
  // Training and documentation only, and only on an empty development database.
  if (process.env.AMRIT_DEMO_SEED && !app.isPackaged) seedDemoData(database)
  vault = new CredentialVault(app.getPath('userData'))
  await migrateLegacySecrets()
  const aggregateExecutor = createAggregateExecutor({
    listIsolates: (labCode) => database.listRecords({ labCode, includeDrafts: false, limit: 100_000 }),
    getLaboratory: (labCode) => database.getLab(labCode)
  })
  syncManager = new SyncManager({
    executor: aggregateExecutor,
    tokenStore: { get: () => vault.get(SYNC_TOKEN_KEY), set: (token) => vault.set(SYNC_TOKEN_KEY, token) },
    listOneHealthOutbox: (limit) => database.listOneHealthOutbox(limit),
    markOneHealthOutboxSent: (id) => database.markOneHealthOutboxSent(id),
    markOneHealthOutboxFailure: (id, error) => database.markOneHealthOutboxFailure(id, error),
    appVersion: app.getVersion(),
    onStatus: broadcastSyncStatus,
    onAudit: (event) => database.recordAudit(`sync.${event.type}`, event.status, event.summary || event.error || event.query_id, event as unknown as Record<string, unknown>)
  })
  // Resume a pending approval after an application restart. The pickup proof itself stays
  // encrypted; only its non-secret expiry timestamp lives in preferences.
  const pendingConfig = await loadSyncConfig()
  if (!pendingConfig.authToken && pendingConfig.pickupToken && pendingConfig.serverUrl && pendingConfig.labCode) {
    beginAccessTokenCollection(
      pendingConfig,
      5,
      database.getPreferences().sync_pickup_expires_at ?? ''
    )
  }
  registerIpc()
  app.setName(activeCountryProfile().branding?.product_name || 'AMRIT')
  createWindow()
}

app.setName('AMRIT')
const lock = app.requestSingleInstanceLock()
if (!lock) app.quit()
else {
  app.on('second-instance', () => {
    if (!mainWindow) return
    if (mainWindow.isMinimized()) mainWindow.restore()
    mainWindow.focus()
  })
  app.whenReady().then(async () => {
    installApplicationMenu()
    // Everything is denied except the one permission this application asks for on purpose.
    //
    // Location is requested only from the sync settings screen, only after the operator has
    // ticked the site-coordinate consent, and it places the *laboratory*, never a patient.
    // Granting it here is what lets `navigator.geolocation` reach the operating system's own
    // location service; without it Chromium refuses before the OS is ever asked.
    session.defaultSession.setPermissionRequestHandler((webContents, permission, callback) => {
      callback(permission === 'geolocation' && isOwnContent(webContents.getURL()))
    })
    // Chromium also asks synchronously, and a handler that answers only the async question
    // leaves the synchronous check at its default.
    session.defaultSession.setPermissionCheckHandler((_webContents, permission, origin) => (
      permission === 'geolocation' && isOwnContent(origin)
    ))
    await initialize()
    app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow() })
  }).catch((error) => {
    dialog.showErrorBox(`${app.getName()} could not start`, errorMessage(error))
    app.quit()
  })
  app.on('before-quit', () => { enrolmentController?.abort(); void syncManager?.stop(); database?.close() })
  app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit() })
}
