# Generated by Django 6.0.4 on 2026-07-10 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('scope_type', models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District'), ('site', 'Site / facility')], db_index=True, default='national', max_length=16)),
                ('scope_value', models.CharField(blank=True, db_index=True, max_length=120)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('n_sites', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('snapshot', 'Scheduled snapshot'), ('live', 'On-demand live pull'), ('seed', 'Seeded demo')], default='snapshot', max_length=16)),
                ('is_stale', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['metric_key', 'scope_type', 'scope_value', '-computed_at'], name='dashboards__metric__9d0b26_idx')],
            },
        ),
    ]
