# Generated by Django 6.0.4 on 2026-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_mark_legacy_snapshots_stale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardrefreshrun",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("national", "National"),
                    ("state", "State"),
                    ("district", "District"),
                    ("site", "Site / facility"),
                    ("global", "Global (all countries)"),
                    ("country", "Country"),
                    ("admin:1", "Administrative level 1"),
                    ("admin:2", "Administrative level 2"),
                    ("admin:3", "Administrative level 3"),
                    ("admin:4", "Administrative level 4"),
                    ("admin:5", "Administrative level 5"),
                    ("admin:6", "Administrative level 6"),
                ],
                db_index=True,
                default="national",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="kpisnapshot",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("national", "National"),
                    ("state", "State"),
                    ("district", "District"),
                    ("site", "Site / facility"),
                    ("global", "Global (all countries)"),
                    ("country", "Country"),
                    ("admin:1", "Administrative level 1"),
                    ("admin:2", "Administrative level 2"),
                    ("admin:3", "Administrative level 3"),
                    ("admin:4", "Administrative level 4"),
                    ("admin:5", "Administrative level 5"),
                    ("admin:6", "Administrative level 6"),
                ],
                db_index=True,
                default="national",
                max_length=16,
            ),
        ),
    ]
