#!/usr/bin/env python3
"""Run the official HL7 FHIR validator over the reference corpus. Zero errors is a merge gate.

Phase 25, and the single most valuable line in it: *"The official HL7 FHIR validator runs in CI
against a reference corpus, and zero errors is a merge gate. This converts 'we support FHIR' into
a build that fails when we stop."*

Two things make the gate mean something rather than decorate the build:

**The corpus is generated by the exporter.** `app/scripts/generate-reference-corpus.ts` produces
`fhir-ig/reference-corpus/` by running `createExport`, and has its own `--check`. Validating a
hand-written file would prove a hand-written file is valid FHIR and nothing about the product.

**The validator is pinned.** `latest` would mean a validator release could fail an unrelated
commit on a day nobody touched FHIR, and — worse — that a green build could not be reproduced.
Bumping VERSION is a deliberate act with its own diff.

    python3 tools/validate_fhir_corpus.py              # fetch if needed, validate, fail on error
    python3 tools/validate_fhir_corpus.py --jar PATH   # use a jar already on disk

The validator needs a network: it resolves `hl7.fhir.r4.core` and friends from the package
registry and checks codes against `tx.fhir.org`. That is a feature — the LOINC and UCUM codes
AMRIT emits are checked against the real terminology server, not against our own copy of it.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
import urllib.request
from collections import Counter
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CORPUS = REPOSITORY_ROOT / "fhir-ig" / "reference-corpus"
# Both are needed. `fsh-generated` holds the profiles; `input/resources` holds the generated
# CodeSystems and ValueSets. Loading only the first leaves `urn:whonet:*` unresolvable, which
# the validator reports as a warning per coding — seven of them on the first run.
IG_PATHS = [
    REPOSITORY_ROOT / "fhir-ig" / "fsh-generated" / "resources",
    REPOSITORY_ROOT / "fhir-ig" / "input" / "resources",
]

VERSION = "6.10.2"
URL = f"https://github.com/hapifhir/org.hl7.fhir.core/releases/download/{VERSION}/validator_cli.jar"
FHIR_VERSION = "4.0.1"

# Set by CI to a cached path so the 180 MB jar is downloaded once per runner, not per job.
JAR_ENVIRONMENT_VARIABLE = "AMRIT_FHIR_VALIDATOR_JAR"


def cache_path() -> Path:
    root = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
    return root / "amrit" / "fhir-validator" / f"validator_cli-{VERSION}.jar"


def resolve_jar(explicit: str | None) -> Path:
    if explicit:
        path = Path(explicit).expanduser().resolve()
        if not path.is_file():
            sys.exit(f"No validator jar at {path}")
        return path
    from_environment = os.environ.get(JAR_ENVIRONMENT_VARIABLE)
    if from_environment and Path(from_environment).is_file():
        return Path(from_environment)
    cached = cache_path()
    if cached.is_file():
        return cached
    cached.parent.mkdir(parents=True, exist_ok=True)
    print(f"Fetching the official FHIR validator {VERSION} (about 180 MB, once)...", flush=True)
    # Download beside the target and rename, so an interrupted fetch cannot leave a truncated
    # jar that looks cached and then fails with an unreadable Java error on the next run.
    with tempfile.NamedTemporaryFile(dir=cached.parent, delete=False, suffix=".part") as scratch:
        partial = Path(scratch.name)
    try:
        urllib.request.urlretrieve(URL, partial)
        partial.replace(cached)
    except Exception:
        partial.unlink(missing_ok=True)
        raise
    return cached


def java_present() -> bool:
    try:
        subprocess.run(["java", "-version"], capture_output=True, check=True)
        return True
    except (OSError, subprocess.CalledProcessError):
        return False


def validate(jar: Path, sources: list[Path]) -> list[dict]:
    with tempfile.TemporaryDirectory() as scratch:
        output = Path(scratch) / "outcome.json"
        command = ["java", "-jar", str(jar), *[str(path) for path in sources],
                   "-version", FHIR_VERSION]
        for path in IG_PATHS:
            command += ["-ig", str(path)]
        command += ["-output", str(output)]
        completed = subprocess.run(command, capture_output=True, text=True)
        if not output.is_file():
            print(completed.stdout[-4000:])
            print(completed.stderr[-4000:], file=sys.stderr)
            sys.exit(f"The validator produced no report (exit {completed.returncode}).")
        report = json.loads(output.read_text(encoding="utf-8"))
    # One source produces an OperationOutcome; several produce a Bundle of them.
    if report.get("resourceType") == "Bundle":
        return [issue
                for entry in report.get("entry", [])
                for issue in entry.get("resource", {}).get("issue", [])]
    return report.get("issue", [])


def describe(issue: dict) -> str:
    location = (issue.get("expression") or issue.get("location") or ["(no location)"])[0]
    return f"  [{issue['severity']}] {location}\n      {issue.get('details', {}).get('text', '')}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jar", help="Path to validator_cli.jar; otherwise cached or fetched.")
    arguments = parser.parse_args()

    if not java_present():
        sys.exit("This gate needs a Java runtime and `java -version` failed. "
                 "The validator is a Java application; there is no pure-Python substitute, and "
                 "skipping it silently would turn a merge gate into a decoration.")

    sources = sorted(CORPUS.glob("*.json"))
    if not sources:
        sys.exit(f"No corpus to validate in {CORPUS}. Run "
                 "`npx jiti scripts/generate-reference-corpus.ts` from app/ first.")

    jar = resolve_jar(arguments.jar)
    print(f"Validating {len(sources)} file(s) against FHIR {FHIR_VERSION} "
          f"with validator {VERSION}:")
    for source in sources:
        print(f"  {source.relative_to(REPOSITORY_ROOT)}")

    issues = validate(jar, sources)
    counts = Counter(issue["severity"] for issue in issues)
    failures = [issue for issue in issues if issue["severity"] in {"error", "fatal"}]

    for severity in ("fatal", "error", "warning", "information"):
        shown = [issue for issue in issues if issue["severity"] == severity]
        if shown:
            print(f"\n{severity}: {len(shown)}")
            for issue in shown:
                print(describe(issue))

    print(f"\nTotals: {dict(counts) or 'no issues'}")
    if failures:
        print(f"\nFAIL — {len(failures)} error(s). Zero errors is the gate.")
        return 1
    print("\nPASS — zero errors. Warnings above are reviewed in "
          "docs/expansion/PHASE_STATUS.md, not suppressed here.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
