# Generated by Django 6.0.4 on 2026-07-10 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=12)),
                ('summary', models.TextField(blank=True)),
                ('default_action_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('scope_type', models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District'), ('site', 'Site / facility')], default='national', max_length=16)),
                ('comparator', models.CharField(choices=[('gt', 'greater than'), ('gte', 'greater than or equal'), ('lt', 'less than'), ('lte', 'less than or equal')], default='gte', max_length=4)),
                ('threshold', models.FloatField(help_text="Compared against the metric's headline value (e.g. %R).")),
                ('severity', models.CharField(choices=[('info', 'Info'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=12)),
                ('target_role', models.CharField(blank=True, help_text='Role the plan is addressed to.', max_length=32)),
                ('title_template', models.CharField(blank=True, max_length=200)),
                ('body_template', models.TextField(blank=True)),
                ('default_action_points', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['metric_key', '-threshold'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('trigger_metric_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('observed_value', models.FloatField(blank=True, null=True)),
                ('scope_type', models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District'), ('site', 'Site / facility')], db_index=True, default='national', max_length=16)),
                ('scope_value', models.CharField(blank=True, db_index=True, max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='moderate', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('dismissed', 'Dismissed')], db_index=True, default='draft', max_length=16)),
                ('target_role', models.CharField(blank=True, db_index=True, max_length=32)),
                ('is_auto', models.BooleanField(default=False, help_text='Raised by the threshold rule engine.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_plans', to=settings.AUTH_USER_MODEL)),
                ('trigger_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='dashboards.kpisnapshot')),
                ('threshold_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='actionplans.thresholdrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('owner_role', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], db_index=True, default='open', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_action_points', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='actionplans.actionplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActionTakenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField()),
                ('evidence_numbers_json', models.JSONField(blank=True, default=dict, help_text='Aggregate KPI values cited (no patient data).')),
                ('attachment_url', models.URLField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atrs', to='actionplans.actionpoint')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atrs', to='actionplans.actionplan')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_atrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actionplan',
            index=models.Index(fields=['scope_type', 'scope_value', 'status'], name='actionplans_scope_t_4472a5_idx'),
        ),
    ]
