# Generated by Django 6.0.4 on 2026-08-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actionplans", "0003_canonical_scope_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionplan",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("site", "Site / facility"),
                    ("global", "Global (all countries)"),
                    ("country", "Country"),
                    ("admin:1", "Administrative level 1"),
                    ("admin:2", "Administrative level 2"),
                    ("admin:3", "Administrative level 3"),
                    ("admin:4", "Administrative level 4"),
                    ("admin:5", "Administrative level 5"),
                    ("admin:6", "Administrative level 6"),
                ],
                db_index=True,
                default="country",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="thresholdrule",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("site", "Site / facility"),
                    ("global", "Global (all countries)"),
                    ("country", "Country"),
                    ("admin:1", "Administrative level 1"),
                    ("admin:2", "Administrative level 2"),
                    ("admin:3", "Administrative level 3"),
                    ("admin:4", "Administrative level 4"),
                    ("admin:5", "Administrative level 5"),
                    ("admin:6", "Administrative level 6"),
                ],
                default="country",
                max_length=16,
            ),
        ),
    ]
