"""One postal address shape for every country.

A site used to be located by a free-text ``state`` and ``district``. That is India's model
with India's words; it cannot say where a building is in Japan, Ireland or the United Arab
Emirates. This module holds the server side of the replacement: the ISO 19160-1 /
libaddressinput field set, driven by the same per-country format pack the desktop app uses,
so an address means the same thing on both sides of the sync.

Two different questions are deliberately kept apart:

  - *which reporting unit is this under* — the AdminUnit tree, ``Site.admin_unit`` and
    ``admin_path``, which is what every scope filter matches on;
  - *how is an address written here* — everything in this module.

They are joined by ``admin_area_code`` (ISO 3166-2) and never conflated, because a
facility's postal town and its reporting district are frequently not the same place.

This is the address of a facility, never of a person: there is no recipient line, and none
should be added.

The behaviour here mirrors ``app/src/shared/address.ts`` function for function. Both read
the same pack, and ``test_address.py`` pins the two against the same cases, because an
address that renders one way on the desktop and another on the portal is the same defect as
not storing it at all.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Iterable

from .directory import is_at_least_as_precise
from .open_location_code import normalize_plus_code, plus_code_problem, point_from_plus_code

SHARED_ROOT = Path(__file__).resolve().parent.parent / "shared"
PACK_PATH = SHARED_ROOT / "address-formats" / "address-formats.v1.json"

# The order a form renders fields in when a country's format string places none of them.
FIELD_ORDER = (
    "recipient",
    "organization",
    "address_lines",
    "dependent_locality",
    "locality",
    "admin_area",
    "postal_code",
    "sorting_code",
)

# What this software stores. ``recipient`` is not one of them: these are the addresses of
# facilities, and an attention line is where a person's name ends up.
STORED_FIELDS = tuple(field for field in FIELD_ORDER if field != "recipient")

# The precisions a stored coordinate may claim. Mirrors GEO_PRECISIONS in
# app/src/shared/geo-directory.ts; see geo/directory.py for what each one means.
GEO_PRECISIONS = ("device", "manual", "plus_code", "postal_area", "locality", "subdivision", "country")

# Single-string components, in the order they are normalised.
COMPONENT_FIELDS = ("dependent_locality", "locality", "admin_area", "postal_code", "sorting_code", "organization")

TOKEN_FIELD = {
    "N": "recipient",
    "O": "organization",
    "A": "address_lines",
    "D": "dependent_locality",
    "C": "locality",
    "S": "admin_area",
    "Z": "postal_code",
    "X": "sorting_code",
}

# Always acceptable, whatever a country's format string places.
UNIVERSAL_FIELDS = frozenset({"address_lines", "organization"})

_TOKEN_RE = re.compile(r"%([A-Z])")
_TOKEN_SPLIT_RE = re.compile(r"(%[A-Z])")


class AddressError(ValueError):
    """Raised when an address cannot be stored as given for its country."""


@lru_cache(maxsize=1)
def address_format_pack() -> dict[str, Any]:
    """The bundled pack, read once.

    Generated by ``tools/generate_address_formats.py`` and checked in, so this only reads
    it. Nothing here carries per-country knowledge.
    """
    if not PACK_PATH.exists():
        raise AddressError(
            f"Address format pack not found at {PACK_PATH}. Run python3 tools/sync_shared.py in a source checkout."
        )
    pack = json.loads(PACK_PATH.read_text(encoding="utf-8"))
    if not pack.get("default") or not pack.get("countries"):
        raise AddressError(f"Address format pack at {PACK_PATH} is missing its default entry or country table.")
    return pack


def address_format_for(country_code: str) -> dict[str, Any]:
    """The address form for a country.

    A country the pack has no entry for falls back to the pack's own default, which is a
    working address form rather than an error: a deployment in an unlisted territory is
    never blocked from recording where its laboratories are.
    """
    pack = address_format_pack()
    key = str(country_code or "").strip().upper()
    return pack["countries"].get(key) or pack["default"]


def _text(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ""


def value_for(field: str, address: dict[str, Any]) -> str:
    """The value a token stands for, as text.

    ``address_lines`` is the only multi-line field and keeps its own line breaks rather
    than being flattened.
    """
    if field == "address_lines":
        lines = address.get("address_lines") or []
        if isinstance(lines, str):
            lines = [lines]
        return "\n".join(line for line in (_text(item) for item in lines) if line)
    if field == "recipient":
        return ""
    return _text(address.get(field))


def _apply_uppercase(field: str, value: str, fmt: dict[str, Any]) -> str:
    return value.upper() if field in (fmt.get("uppercase") or []) else value


def _tidy(line: str) -> str:
    """Tidy what token substitution leaves behind.

    ``%C, %S %Z`` with no admin area would otherwise render ``Kochi,  682011`` — the
    separator belongs to a field that is not there.
    """
    line = re.sub(r"[ \t]+", " ", line)
    line = re.sub(r"\s*,\s*,\s*", ", ", line)
    line = re.sub(r"^[\s,\-–]+", "", line)
    line = re.sub(r"[\s,\-–]+$", "", line)
    return line.strip()


def format_address(address: dict[str, Any], fmt: dict[str, Any] | None = None) -> str:
    """Render an address using its country's format string.

    A line whose every field is empty is dropped entirely, including its literal text: a
    Singapore address with no postal code must not render the bare word ``SINGAPORE``. A
    line with no fields at all is literal and always kept.
    """
    fmt = fmt or address_format_for(address.get("country_code", ""))
    lines: list[str] = []
    for template in str(fmt.get("format") or "").split("%n"):
        tokens = _TOKEN_RE.findall(template)
        rendered = ""
        any_value = False
        # Substituted piece by piece rather than by replacement, so the separator that
        # belonged to an absent field goes with it: `%C, %S %Z` with no state renders
        # "Atlanta 30329", not "Atlanta, 30329".
        for piece in _TOKEN_SPLIT_RE.split(template):
            if not piece:
                continue
            token = piece[1:] if _TOKEN_RE.fullmatch(piece) else ""
            if not token:
                rendered += piece
                continue
            field = TOKEN_FIELD.get(token)
            value = _apply_uppercase(field, value_for(field, address), fmt) if field else ""
            if value:
                any_value = True
                rendered += value
            else:
                rendered = rendered.rstrip(" \t,-–")
        if tokens and not any_value:
            continue
        # %A can expand to several lines; each is tidied on its own.
        for part in rendered.split("\n"):
            cleaned = _tidy(part)
            if cleaned:
                lines.append(cleaned)
    return "\n".join(lines)


def label_token_for(field: str, fmt: dict[str, Any]) -> str:
    """The country's token for a field: ``state``, ``prefecture``, ``pin``, ``eircode``.

    A stable identifier, not display text — it is the key a translation catalogue is written
    against. Mirrors ``labelTokenFor`` in ``app/src/shared/address.ts``.
    """
    return str((fmt.get("labels") or {}).get(field) or field)


def label_for(field: str, fmt: dict[str, Any]) -> str:
    """What this country calls a field, in English sentence case.

    The fallback for anywhere without a translation catalogue. It used to return the source
    dataset's raw lower-case token, which is how "pin" and "state" reached the screen as
    field labels.
    """
    return label_token_for(field, fmt).replace("_", " ").capitalize()


def _postal_code_matches(value: str, pattern: str) -> bool:
    """Anchor a country's postal pattern.

    The pack's patterns match a whole code, not a substring, so an unanchored test would
    accept ``XX12345XX`` for a five-digit country. A pattern this engine cannot compile is
    treated as passing: the pack is data, and bad data must not become a data-entry wall.
    """
    try:
        return re.fullmatch(pattern, value) is not None
    except re.error:
        return True


def validate_address(address: dict[str, Any], fmt: dict[str, Any] | None = None) -> list[dict[str, str]]:
    """Check an address against its country's rules.

    Returns problems rather than raising, so a form can show all of them at once instead of
    one per submission.
    """
    fmt = fmt or address_format_for(address.get("country_code", ""))
    problems: list[dict[str, str]] = []

    if not re.fullmatch(r"[A-Z]{3}", _text(address.get("country_code")).upper()):
        problems.append(
            {
                "field": "country_code",
                "code": "country_code",
                "message": "Country is required, as an ISO 3166-1 alpha-3 code.",
            }
        )

    for field in STORED_FIELDS:
        value = value_for(field, address)
        label = label_for(field, fmt)
        if not value:
            if field in (fmt.get("required") or []):
                problems.append({"field": field, "code": "required", "message": f"{label} is required in this country."})
            continue
        if field not in (fmt.get("fields") or []) and field not in UNIVERSAL_FIELDS:
            # Storing a value the country's format cannot place means it never renders and
            # is never found. Say so at entry rather than losing it quietly.
            problems.append(
                {
                    "field": field,
                    "code": "unsupported",
                    "message": (
                        f"{label} is not part of an address in this country; "
                        "put it in the street address lines instead."
                    ),
                }
            )
            continue
        pattern = fmt.get("postal_code_pattern")
        if field == "postal_code" and pattern and not _postal_code_matches(value, str(pattern)):
            examples = fmt.get("postal_code_examples") or []
            suffix = f" (for example {examples[0]})" if examples else ""
            problems.append(
                {
                    "field": field,
                    "code": "postal_code_pattern",
                    "message": f"{label} does not match the format used in this country{suffix}.",
                }
            )

    plus_problem = plus_code_problem(address.get("plus_code"))
    if plus_problem:
        problems.append({"field": "plus_code", "code": "plus_code", "message": plus_problem})

    return problems


def fields_for_form(fmt: dict[str, Any]) -> list[str]:
    """The fields a form shows for this country, in the order the country writes them."""
    ordered: list[str] = []
    for token in _TOKEN_RE.findall(str(fmt.get("format") or "")):
        field = TOKEN_FIELD.get(token)
        if field and field != "recipient" and field not in ordered:
            ordered.append(field)
    for field in fmt.get("fields") or []:
        if field != "recipient" and field not in ordered:
            ordered.append(field)
    return ordered


def _clean_geo_point(value: Any) -> dict[str, Any] | None:
    """A resolved coordinate, or nothing.

    Dropped rather than refused when it is malformed: a point is derived data that can
    always be resolved again, and losing a site's whole address because a coordinate
    arrived wrong would be the wrong trade. A point without its precision is dropped for
    the same reason it is stored at all — a coordinate whose exactness is unknown cannot be
    filtered, and would be plotted as though it were a street address.
    """
    if not isinstance(value, dict):
        return None
    try:
        latitude = float(value.get("latitude"))
        longitude = float(value.get("longitude"))
    except (TypeError, ValueError):
        return None
    if not (-90 <= latitude <= 90 and -180 <= longitude <= 180):
        return None
    precision = _text(value.get("precision"))
    if precision not in GEO_PRECISIONS:
        return None
    point: dict[str, Any] = {"latitude": latitude, "longitude": longitude, "precision": precision}
    if _text(value.get("source")):
        point["source"] = _text(value.get("source"))
    if _text(value.get("resolved_at")):
        point["resolved_at"] = _text(value.get("resolved_at"))
    return point


def normalize_address(address: dict[str, Any], fmt: dict[str, Any] | None = None) -> dict[str, Any]:
    """Drop empty components and refresh ``formatted``, so what is stored is what renders."""
    country = _text(address.get("country_code")).upper()
    fmt = fmt or address_format_for(country)
    lines = [line for line in (_text(item) for item in (address.get("address_lines") or [])) if line]

    normalized: dict[str, Any] = {"country_code": country}
    if lines:
        normalized["address_lines"] = lines
    for field in COMPONENT_FIELDS:
        value = _apply_uppercase(field, _text(address.get(field)), fmt)
        if value:
            normalized[field] = value
    if _text(address.get("admin_area_code")):
        normalized["admin_area_code"] = _text(address.get("admin_area_code")).upper()
    if _text(address.get("language_code")):
        normalized["language_code"] = _text(address.get("language_code"))
    if address.get("admin_unit_id"):
        normalized["admin_unit_id"] = address["admin_unit_id"]
    plus_code = normalize_plus_code(address.get("plus_code"))
    if plus_code:
        normalized["plus_code"] = plus_code
    point = _clean_geo_point(address.get("geo_point"))
    decoded = point_from_plus_code(
        plus_code,
        at=point.get("resolved_at") if point and point.get("source") == "open-location-code" else None,
    )
    if decoded and (not point or is_at_least_as_precise(decoded["precision"], point.get("precision"))):
        point = decoded
    if point:
        normalized["geo_point"] = point
    rendered = format_address(normalized, fmt)
    if rendered:
        normalized["formatted"] = rendered
    return normalized


def repair_unsupported_address_fields(
    address: dict[str, Any], fmt: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Move components this country's format cannot print into address lines.

    This is lossless migration for imported records and country changes, not relaxed
    validation: required fields, country codes, postal patterns and Plus Codes are still
    checked after the repair.
    """
    fmt = fmt or address_format_for(address.get("country_code", ""))
    repaired = dict(address)
    lines = [line for line in (_text(item) for item in (repaired.get("address_lines") or [])) if line]
    line_keys = {line.casefold() for line in lines}
    for field in STORED_FIELDS:
        value = value_for(field, repaired)
        if not value or field in (fmt.get("fields") or []) or field in UNIVERSAL_FIELDS:
            continue
        if value.casefold() not in line_keys:
            lines.append(value)
            line_keys.add(value.casefold())
        repaired.pop(field, None)
    if lines:
        repaired["address_lines"] = lines
    else:
        repaired.pop("address_lines", None)
    return normalize_address(repaired, fmt)


def clean_address(value: Any, *, country_code: str = "", require_complete: bool = False) -> dict[str, Any]:
    """Validate and normalise one address, or refuse it.

    Two different failures are deliberately treated differently.

    *Unstorable* — no country, a postal code that does not match the country's pattern, or
    an invalid Plus Code — is refused wherever it comes from. A structured component the
    country cannot place is preserved in the street lines before validation.

    *Incomplete* — a field the country normally writes is missing — is *accepted* here.
    A site registry legitimately knows a facility's town before it knows its street, and a
    registry that refuses the row loses the site as well as the address. Completeness is
    enforced where someone is actually filling a form and can be asked for the rest: the
    desktop laboratory editor blocks Save on it. Pass ``require_complete=True`` to demand it.

    An empty value is not an error: a site may be recorded before anyone knows its address.
    """
    if not value:
        return {}
    if not isinstance(value, dict):
        raise AddressError("An address must be an object of address fields.")
    candidate = dict(value)
    candidate["country_code"] = str(candidate.get("country_code") or country_code or "").upper()
    fmt = address_format_for(candidate["country_code"])
    candidate = repair_unsupported_address_fields(candidate, fmt)
    problems = [
        problem for problem in validate_address(candidate, fmt)
        if require_complete or problem["code"] != "required"
    ]
    if problems:
        detail = " ".join(problem["message"] for problem in problems)
        raise AddressError(f"Address is not valid for {candidate['country_code'] or 'the country given'}: {detail}")
    return normalize_address(candidate, fmt)


def to_fhir_address(address: dict[str, Any], fmt: dict[str, Any] | None = None) -> dict[str, Any] | None:
    """FHIR R4 ``Address``.

    One-to-one by construction — the field set was chosen so it would be — except
    ``sorting_code``, which FHIR has no element for and which therefore travels as an
    extension rather than being dropped.
    """
    if not address:
        return None
    resource: dict[str, Any] = {}
    lines = [line for line in (_text(item) for item in (address.get("address_lines") or [])) if line]
    if lines:
        resource["line"] = lines
    if _text(address.get("locality")):
        resource["city"] = _text(address.get("locality"))
    if _text(address.get("dependent_locality")):
        resource["district"] = _text(address.get("dependent_locality"))
    if _text(address.get("admin_area")):
        resource["state"] = _text(address.get("admin_area"))
    if _text(address.get("postal_code")):
        resource["postalCode"] = _text(address.get("postal_code"))
    if _text(address.get("country_code")):
        resource["country"] = _text(address.get("country_code"))

    rendered = _text(address.get("formatted")) or (format_address(address, fmt) if fmt else "")
    if rendered:
        resource["text"] = rendered
    extensions: list[dict[str, Any]] = []
    if _text(address.get("sorting_code")):
        extensions.append(
            {
                "url": "https://schemas.amrit-amr.org/fhir/StructureDefinition/address-sorting-code",
                "valueString": _text(address.get("sorting_code")),
            }
        )
    if _text(address.get("plus_code")):
        extensions.append(
            {
                "url": "https://schemas.amrit-amr.org/fhir/StructureDefinition/address-plus-code",
                "valueString": normalize_plus_code(address.get("plus_code")),
            }
        )
    if extensions:
        resource["extension"] = extensions
    return resource or None


def address_summary(address: dict[str, Any], *, separator: str = ", ") -> str:
    """One-line rendering, for a table cell or a log line."""
    if not address:
        return ""
    rendered = _text(address.get("formatted")) or format_address(address)
    return separator.join(part for part in rendered.split("\n") if part)


def address_search_text(address: dict[str, Any]) -> str:
    """Everything in an address as one searchable string, in no particular order."""
    parts: Iterable[str] = (value_for(field, address) for field in STORED_FIELDS)
    searchable = [part.replace("\n", " ") for part in parts if part]
    if normalize_plus_code(address.get("plus_code")):
        searchable.append(normalize_plus_code(address.get("plus_code")))
    return " ".join(searchable)
